import { NextResponse } from "next/server";
import { getDb } from "@/lib/db";

// GET /api/recruita/candidates/prefill?line_user_id=...
//
// Public endpoint — no auth required. The LINE userId is a 128-bit
// random string generated by LINE and acts as an opaque secret; it
// is not guessable by anyone who hasn't followed the OA.
//
// Returns a subset of the candidate's most recent data that is safe
// to pre-populate into the apply form on their return. Specifically:
//   • national_id is EXCLUDED (stored encrypted; decryption would
//     require the vault key on a public endpoint, which is a bad idea)
//   • custom (per-position answers) is EXCLUDED — they don't carry
//     over across positions
//   • pdpa_consent / truth_declaration_accepted are EXCLUDED — the
//     candidate must re-affirm consent for each new application
//
// Returns 200 { candidate: {...FormState fields} }
//      or 204 when no candidate found (first-time applicant)
//
// Rate limiting: rely on LINE userId obscurity for now. If this
// endpoint ever gets hammered, add per-IP rate limiting at the
// Nginx layer.

export async function GET(req: Request) {
  const url = new URL(req.url);
  const lineUserId = (url.searchParams.get("line_user_id") ?? "").trim();

  // Minimum sanity — LINE UIDs start with "U" followed by 32 hex chars
  if (!lineUserId || !/^U[0-9a-fA-F]{32}$/.test(lineUserId)) {
    return NextResponse.json({ error: "invalid_line_user_id" }, { status: 400 });
  }

  const db = getDb();
  const row = db.prepare(`
    SELECT
      title_prefix, first_name_th, last_name_th,
      first_name_en, last_name_en, nickname_th,
      dob, gender, nationality, race, marital_status,
      military_status, religion,
      personal_email, mobile_phone, line_id, house_address, housing_type,
      professional_license_status,
      prior_illness, prior_illness_detail, prior_application_at,
      emergency_name, emergency_relationship, emergency_phone,
      referee_external_text,
      education_json, experience_json, skills_language_json, skills_other
    FROM recruita_candidates
    WHERE line_user_id = ?
    LIMIT 1
  `).get(lineUserId) as Record<string, unknown> | undefined;

  if (!row) {
    // 204 = "found but no content" — ApplyClient treats this as first-time applicant
    return new NextResponse(null, { status: 204 });
  }

  // Parse JSON columns
  function parseJsonArr(v: unknown): unknown[] {
    if (typeof v !== "string") return [];
    try { const p = JSON.parse(v); return Array.isArray(p) ? p : []; }
    catch { return []; }
  }

  // Convert prior_illness (0/1/null) back to "yes"/"no"/"" string
  const priorIllness = row.prior_illness === 1 ? "yes"
    : row.prior_illness === 0 ? "no"
    : "";

  const candidate = {
    title_prefix:     row.title_prefix     ?? "",
    first_name_th:    row.first_name_th    ?? "",
    last_name_th:     row.last_name_th     ?? "",
    first_name_en:    row.first_name_en    ?? "",
    last_name_en:     row.last_name_en     ?? "",
    nickname_th:      row.nickname_th      ?? "",
    dob:              row.dob              ?? "",
    gender:           row.gender           ?? "",
    nationality:      row.nationality      ?? "",
    race:             row.race             ?? "",
    marital_status:   row.marital_status   ?? "",
    military_status:  row.military_status  ?? "",
    religion:         row.religion         ?? "",
    personal_email:   row.personal_email   ?? "",
    mobile_phone:     row.mobile_phone     ?? "",
    line_id:          row.line_id          ?? "",
    house_address:    row.house_address    ?? "",
    housing_type:     row.housing_type     ?? "",
    professional_license_status: row.professional_license_status ?? "",
    prior_illness:         priorIllness,
    prior_illness_detail:  row.prior_illness_detail  ?? "",
    prior_application_at:  row.prior_application_at  ?? "",
    emergency_name:         row.emergency_name         ?? "",
    emergency_relationship: row.emergency_relationship ?? "",
    emergency_phone:        row.emergency_phone        ?? "",
    referee_external_text:  row.referee_external_text  ?? "",
    education:        parseJsonArr(row.education_json),
    experience:       parseJsonArr(row.experience_json),
    skills_language:  parseJsonArr(row.skills_language_json),
    skills_other:     row.skills_other ?? ""
  };

  return NextResponse.json({ candidate });
}
