// SALESA proof — POS file parsers + DB upsert + daily/weekly analytics.
//
// Self-contained: builds throwaway .xlsx buffers shaped like the FeedMe
// "Close up" (KPI) and "Overview" (menu-revenue) exports, then a throwaway DB
// with one branch, and proves:
//   • parseCloseUp reads the aggregate KPIs (Nett/bills/discount/payments/types)
//   • parseOverview ranks categories + individual menus by revenue (desc)
//   • upsert + dailyAnalytics (discount %, prev-day + 7-day compare, top/bottom)
//   • weeklyAnalytics (Mon–Sun total, best day, menu aggregation across days)
//   • clearDay removes a day
//
// Run:  node --import tsx scripts/test-salesa.ts   (or: npm run test:salesa)

import fs from "node:fs";
import path from "node:path";
import * as XLSX from "xlsx";

const TMP = path.join(process.cwd(), "data", "test-salesa.db");
function cleanup() {
  for (const f of [TMP, `${TMP}-wal`, `${TMP}-shm`]) {
    try { fs.rmSync(f, { force: true }); } catch { /* ignore */ }
  }
}
cleanup();
fs.mkdirSync(path.dirname(TMP), { recursive: true });
process.env.DATABASE_PATH = TMP;

// ── Build a workbook buffer from { sheetName: rows } ──
function wbBuf(sheets: Record<string, unknown[][]>): Buffer {
  const wb = XLSX.utils.book_new();
  for (const [name, rows] of Object.entries(sheets)) {
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(rows), name.slice(0, 31));
  }
  return XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
}
function preamble(title: string, date: string, merchant: string): unknown[][] {
  return [[title], [`Date: ${date} - ${date}`], ["Time: 00:00 - 23:59"], [`Merchant: ${merchant}`], ["Generated by: test"], []];
}
/** A "Name/Value" scalar sheet. */
function scalar(title: string, date: string, merchant: string, name: string, value: string): unknown[][] {
  return [...preamble(title, date, merchant), ["Name", "Value"], [name, value]];
}

function receiptBuf(date: string, merchant: string, bills: Array<{ time: string; no: string; table: string; gross: string; discount: string; nett: string; payment: string; items: string }>): Buffer {
  const header = ["Time", "No.", "Table", "Status", "ID", "Gross", "Discount", "VAT", "SC", "Other Charge", "Delivery fee", "Rounding", "Nett", "Payment", "Items"];
  const rows = bills.map((b) => [b.time, b.no, b.table, "COMPLETED", "id", b.gross, b.discount, "0", "0", "0", "0", "0", b.nett, b.payment, b.items]);
  return wbBuf({ "1.": [...preamble("Receipt", date, merchant), header, ...rows] });
}

function closeUpBuf(date: string, merchant: string): Buffer {
  const P = (label: string, val: string) => scalar("Close up", date, merchant, label, val);
  return wbBuf({
    "1.Bill count": P("Bill count", "23"),
    "2.Total Sales": P("Total Sales", "14,658"),
    "3.Total Pax": P("Total Pax", "43"),
    "4.Total Discount": P("Total Discount", "-2,105"),
    "8.Average Sales": P("Average Sales", "666.27"),
    "9.Average Pax": P("Average Pax", "1.95"),
    "10.Average Sales Pax": P("Average Sales Pax", "340.88"),
    "11.Payment summary": [...preamble("Close up", date, merchant), ["Name", "Refund", "Qty", "Total"], ["PromptPay", "No", "20", "13,245"], ["Mastercard Credit card", "No", "1", "1,413"]],
    "15.Type summary": [...preamble("Close up", date, merchant), ["Type", "Qty", "Sales"], ["QR", "15", "13,560"], ["TAKEAWAY", "7", "1,098"], ["DINE IN", "1", "0"]],
    "18.Sales summary": [...preamble("Close up", date, merchant), ["Label", "Value"], ["Gross", "15,201"], ["Discount", "-2,105"], ["Gross before charges", "13,096"], ["Service charge", "603.46"], ["VAT", "958.97"], ["Rounding", "-0.43"], ["Nett", "14,658"]]
  });
}
function overviewBuf(date: string, merchant: string, items: Array<[string, string]>, cats: Array<[string, string]>): Buffer {
  const catHeader = ["Dataset", ...cats.map((c) => c[0])];
  const catNett = ["Nett", ...cats.map((c) => c[1])];
  return wbBuf({
    "1.Top products": [...preamble("Overview", date, merchant), catHeader, catNett],
    "4.Top products": [...preamble("Overview", date, merchant), ["Name", "Value"], ...items]
  });
}

(async () => {
  const parse = await import("../src/lib/salesa-parse");
  const { getDb } = await import("../src/lib/db");
  const sdb = await import("../src/lib/salesa-db");
  const analytics = await import("../src/lib/salesa-analytics");

  let passed = 0, failed = 0;
  const ok = (name: string, cond: boolean) => {
    if (cond) { passed++; console.log(`  ✓ ${name}`); }
    else { failed++; console.error(`  ✗ FAIL: ${name}`); }
  };
  const near = (a: number, b: number) => Math.abs(a - b) < 0.01;

  // ── 1) parseCloseUp ──
  const cu = parse.parseCloseUp(closeUpBuf("16/09/2026", "TESTBR"));
  ok("close_up date CE", cu.date === "2026-09-16");
  ok("close_up merchant", cu.merchant === "TESTBR");
  ok("close_up nett", cu.nett === 14658);
  ok("close_up gross", cu.gross === 15201);
  ok("close_up discount negative", cu.discount === -2105);
  ok("close_up vat", near(cu.vat, 958.97));
  ok("close_up bill count", cu.billCount === 23);
  ok("close_up pax", cu.pax === 43);
  ok("close_up avg per head", near(cu.avgSalesPax, 340.88));
  ok("close_up payments parsed", cu.payments.length === 2 && cu.payments.some((p) => p.name === "PromptPay" && p.total === 13245));
  ok("close_up types parsed", cu.types.find((t) => t.name === "QR")?.sales === 13560);
  ok("isCloseUp true / isOverview false", parse.isCloseUp(closeUpBuf("16/09/2026", "X")) && !parse.isOverview(closeUpBuf("16/09/2026", "X")));

  // ── 2) parseOverview (ranked desc) ──
  const ov = parse.parseOverview(overviewBuf("16/09/2026", "TESTBR",
    [["คอหมูย่าง", "1206.14"], ["เนื้อพิคันย่างถ่าน", "1613.8"], ["ยำมาม่า", "782.63"]],
    [["ส้มตำ", "2561.63"], ["ย่าง", "2819.93"]]));
  ok("overview items sorted desc", ov.items[0].name === "เนื้อพิคันย่างถ่าน" && ov.items[0].nett === 1613.8);
  ok("overview items tail lowest", ov.items[ov.items.length - 1].name === "ยำมาม่า");
  ok("overview categories sorted desc", ov.categories[0].name === "ย่าง" && ov.categories[0].nett === 2819.93);
  ok("parseSalesFile dispatch", parse.parseSalesFile(overviewBuf("16/09/2026", "X", [["a", "10"]], [["b", "20"]])).kind === "overview");

  // ── receipt parser ──
  const rbuf = receiptBuf("17/09/2026", "TESTBR", [
    { time: "17/09/2026 12:07:20", no: "1", table: "G2", gross: "1,000", discount: "-100", nett: "1,000", payment: "PromptPay", items: "1x ข้าวสวย,1x คอหมูย่าง,2x ข้าวเหนียว" },
    { time: "17/09/2026 19:30:00", no: "2", table: "C2", gross: "500", discount: "-50", nett: "500", payment: "PromptPay", items: "1x คอหมูย่าง,1x ข้าวเหนียว\t\t, 1x  โค้ก " },
    { time: "17/09/2026 20:00:00", no: "3", table: "STAFF", gross: "300", discount: "-300", nett: "0", payment: "", items: "1x ข้าวสวย,1x ปลาทู" }
  ]);
  const rp = parse.parseSalesFile(rbuf);
  ok("receipt kind + date + merchant", rp.kind === "receipt" && rp.kind === "receipt" && rp.receipt.date === "2026-09-17" && rp.receipt.merchant === "TESTBR");
  if (rp.kind === "receipt") {
    ok("receipt bills parsed (3)", rp.receipt.bills.length === 3);
    const b1 = rp.receipt.bills[0];
    ok("receipt hour + qty aggregation", b1.hour === 12 && b1.items.find((i) => i.name === "ข้าวเหนียว")?.qty === 2);
    ok("receipt name cleaning (tabs/spaces)", !!rp.receipt.bills[1].items.find((i) => i.name === "โค้ก") && !!rp.receipt.bills[1].items.find((i) => i.name === "ข้าวเหนียว"));
    ok("receipt staff flagged", rp.receipt.bills[2].isStaff === true && rp.receipt.bills[0].isStaff === false);
  }

  // ── 3) DB + analytics ──
  const db = getDb();
  const bid = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('r','REST')").run().lastInsertRowid);
  const uid = Number(db.prepare("INSERT INTO users (username,password_hash,display_name,role,status) VALUES ('op','x','ผู้จัดการ','admin','active')").run().lastInsertRowid);

  // A full ISO week: Mon 2026-09-14 … Sun 2026-09-20. Vary the netts.
  const week: Array<{ d: string; nett: number; bills: number; pax: number }> = [
    { d: "2026-09-14", nett: 10000, bills: 20, pax: 30 },
    { d: "2026-09-15", nett: 12000, bills: 22, pax: 35 },
    { d: "2026-09-16", nett: 14658, bills: 23, pax: 43 },
    { d: "2026-09-17", nett: 9000, bills: 18, pax: 25 },
    { d: "2026-09-18", nett: 20000, bills: 30, pax: 55 },
  ];
  for (const w of week) {
    sdb.upsertDaily(bid, uid, {
      date: w.d, dateEnd: w.d, merchant: "REST", nett: w.nett, gross: w.nett + 500, grossBeforeCharges: w.nett - 1000,
      discount: -500, serviceCharge: 100, vat: 200, rounding: 0, deliveryFee: 0, otherCharge: 0,
      billCount: w.bills, pax: w.pax, voidAmount: 0, voidBillCount: 0, refund: 0,
      avgSales: Math.round(w.nett / w.bills), avgPax: w.pax / w.bills, avgSalesPax: Math.round(w.nett / w.pax),
      payments: [{ name: "PromptPay", qty: w.bills, total: w.nett }], types: [], sources: []
    });
  }
  // Menu for two days (aggregation test).
  sdb.upsertMenu(bid, uid, { date: "2026-09-16", dateEnd: "2026-09-16", merchant: "REST",
    categories: [{ name: "ย่าง", nett: 2000 }], items: [
      { name: "คอหมูย่าง", nett: 1200 }, { name: "ปีกไก่", nett: 900 }, { name: "ยำมาม่า", nett: 700 },
      { name: "ลาบ", nett: 500 }, { name: "ต้มแซ่บ", nett: 300 }, { name: "ข้าวเหนียว", nett: 100 }
    ] });
  sdb.upsertMenu(bid, uid, { date: "2026-09-18", dateEnd: "2026-09-18", merchant: "REST",
    categories: [{ name: "ย่าง", nett: 1500 }], items: [{ name: "คอหมูย่าง", nett: 800 }, { name: "ปีกไก่", nett: 600 }] });

  ok("upsert idempotent (re-import same day → still 5 rows)", (() => {
    sdb.upsertDaily(bid, uid, { date: "2026-09-16", dateEnd: "2026-09-16", merchant: "REST", nett: 14658, gross: 15201, grossBeforeCharges: 13096, discount: -2105, serviceCharge: 603.46, vat: 958.97, rounding: -0.43, deliveryFee: 0, otherCharge: 0, billCount: 23, pax: 43, voidAmount: 90, voidBillCount: 1, refund: 0, avgSales: 666.27, avgPax: 1.95, avgSalesPax: 340.88, payments: [], types: [], sources: [] });
    return sdb.listMonth(bid, 2026, 9).length === 5;
  })());

  const a16 = analytics.dailyAnalytics(bid, "2026-09-16")!;
  ok("daily discountPct = |−2105|/15201", near(a16.discountPct ?? 0, (2105 / 15201) * 100));
  ok("daily metrics has 5 headings", a16.metrics.length === 5 && a16.metrics.map((m) => m.key).join(",") === "nett,bills,pax,avgBill,avgHead");
  ok("no WoW/MoM baseline → null (this dataset)", a16.metrics.every((m) => m.wowPct === null && m.momPct === null));
  ok("weekday/dom labels", a16.weekdayTh === "พุธ" && a16.wowLabel === "พุธที่แล้ว" && a16.momLabel === "วันที่ 16 เดือนก่อน");
  ok("daily top item = คอหมูย่าง", a16.topItems[0]?.name === "คอหมูย่าง");
  ok("daily bottom item = ข้าวเหนียว (lowest)", a16.bottomItems[0]?.name === "ข้าวเหนียว");
  // advice: discount ~13.8% (≥8 → warning) + top-earning menu highlight; no
  // WoW/MoM baseline in this dataset so no trend headline.
  ok("advice flags high discount", a16.advice.some((l) => l.includes("ส่วนลดสูง")));
  ok("advice highlights top menu", a16.advice.some((l) => l.includes("คอหมูย่าง")));
  ok("advice capped at 4 lines", a16.advice.length <= 4);

  const wk = analytics.weeklyAnalytics(bid, "2026-09-16");
  ok("weekly Monday anchor", wk.weekStart === "2026-09-14" && wk.weekEnd === "2026-09-20");
  ok("weekly total = sum of 5 days", wk.totalNett === 10000 + 12000 + 14658 + 9000 + 20000);
  ok("weekly best day = 09-18", wk.bestDate === "2026-09-18" && wk.bestNett === 20000);
  ok("weekly bills summed", wk.totalBills === 20 + 22 + 23 + 18 + 30);
  ok("weekly menu aggregated across days (คอหมูย่าง 1200+800)", wk.topItems.find((i) => i.name === "คอหมูย่าง")?.nett === 2000);
  ok("weekly avgPerBill = total/bills", near(wk.avgPerBill ?? 0, wk.totalNett / wk.totalBills));
  ok("weekly WoW null with no prior week (this dataset)", wk.prevWeekNett === null && wk.wowNettPct === null);
  // Fresh branch: clean two adjacent ISO weeks for a WoW check.
  const bid3 = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('r3','REST3')").run().lastInsertRowid);
  const put3 = (d: string, nett: number, bills: number, pax: number) => sdb.upsertDaily(bid3, uid, { date: d, dateEnd: d, merchant: "R3", nett, gross: nett, grossBeforeCharges: nett, discount: 0, serviceCharge: 0, vat: 0, rounding: 0, deliveryFee: 0, otherCharge: 0, billCount: bills, pax, voidAmount: 0, voidBillCount: 0, refund: 0, avgSales: nett / bills, avgPax: pax / bills, avgSalesPax: nett / pax, payments: [], types: [], sources: [] });
  put3("2026-09-08", 100000, 100, 150);  // prev week (09-07..13)
  put3("2026-09-15", 120000, 110, 160);  // this week (09-14..20)
  const wkc = analytics.weeklyAnalytics(bid3, "2026-09-15");
  ok("weekly WoW nett (120000 vs 100000 = +20%)", near(wkc.wowNettPct ?? 0, 20) && wkc.prevWeekNett === 100000);
  ok("weekly WoW bills (110 vs 100 = +10%)", near(wkc.wowBillsPct ?? 0, 10));

  // ── 4) clearDay ──
  ok("clearDay removes the day", (() => {
    sdb.clearDay(bid, "2026-09-17");
    return sdb.getDaily(bid, "2026-09-17") === null && sdb.listMonth(bid, 2026, 9).length === 4;
  })());
  ok("settings round-trip", (() => {
    sdb.setLineGroupId(bid, "  Cabc123  ");
    return sdb.getLineGroupId(bid) === "Cabc123";
  })());

  // ── 5) WoW / MoM / month comparisons on an isolated branch ──
  const bid2 = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('r2','REST2')").run().lastInsertRowid);
  const put = (d: string, nett: number, bills: number, pax: number) => sdb.upsertDaily(bid2, uid, {
    date: d, dateEnd: d, merchant: "R2", nett, gross: nett, grossBeforeCharges: nett, discount: 0,
    serviceCharge: 0, vat: 0, rounding: 0, deliveryFee: 0, otherCharge: 0, billCount: bills, pax,
    voidAmount: 0, voidBillCount: 0, refund: 0, avgSales: nett / bills, avgPax: pax / bills,
    avgSalesPax: nett / pax, payments: [], types: [], sources: []
  });
  put("2026-09-16", 14658, 23, 43);   // target (Wed)
  put("2026-09-09", 13000, 21, 40);   // same weekday last week
  put("2026-08-16", 14000, 24, 45);   // same day-of-month last month
  put("2025-09-05", 50000, 80, 150);  // last year, same month (for YoY MTD)

  const a2 = analytics.dailyAnalytics(bid2, "2026-09-16")!;
  const bills2 = a2.metrics.find((m) => m.key === "bills")!;
  const pax2 = a2.metrics.find((m) => m.key === "pax")!;
  ok("WoW bills vs พุธที่แล้ว (23 vs 21)", near(bills2.wowPct ?? 0, ((23 - 21) / 21) * 100));
  ok("MoM bills vs วันที่16เดือนก่อน (23 vs 24)", near(bills2.momPct ?? 0, ((23 - 24) / 24) * 100));
  ok("WoW pax (43 vs 40)", near(pax2.wowPct ?? 0, ((43 - 40) / 40) * 100));
  ok("MoM pax (43 vs 45)", near(pax2.momPct ?? 0, ((43 - 45) / 45) * 100));
  // nett 14658 vs พุธที่แล้ว 13000 = +12.8% → positive trend headline first.
  ok("advice trend headline WoW-up", a2.advice[0]?.startsWith("ยอดขายสูงกว่าพุธที่แล้ว"));

  const mc = analytics.monthComparison(bid2, 2026, 9, "2026-09-30");
  const mtd = 14658 + 13000; // Sept days ≤30 with sales
  ok("month MTD nett", mc.mtdNett === mtd && mc.throughDay === 30);
  ok("month vs prev month (Aug 14000)", near(mc.prevMonthPct ?? 0, ((mtd - 14000) / 14000) * 100));
  ok("month vs last year (Sep2025 50000)", near(mc.lastYearPct ?? 0, ((mtd - 50000) / 50000) * 100));
  ok("MoM null when target day absent last month", (() => {
    // 2026-03-31 has no 2026-02-31 counterpart → momPct must be null.
    put("2026-03-31", 9000, 10, 12);
    const a3 = analytics.dailyAnalytics(bid2, "2026-03-31")!;
    return a3.metrics.every((m) => m.momPct === null);
  })());

  // ── 6) A weekday · B momentum · D discount · E channels ──
  // Menu momentum: bid week 09-14..20 vs prev week (09-07..13). Add prev-week
  // menu for คอหมูย่าง so it shows as a faller/riser.
  sdb.upsertMenu(bid, uid, { date: "2026-09-10", dateEnd: "2026-09-10", merchant: "REST",
    categories: [], items: [{ name: "คอหมูย่าง", nett: 4000 }, { name: "ปีกไก่", nett: 100 }] });
  const wk2 = analytics.weeklyAnalytics(bid, "2026-09-16");
  // this week คอหมูย่าง = 2000 (16:1200 + 18:800), prev = 4000 → −50% faller.
  ok("momentum faller คอหมูย่าง −50%", !!wk2.menuFallers.find((m) => m.name === "คอหมูย่าง" && near(m.deltaPct ?? 0, -50)));
  ok("momentum riser ปีกไก่ (1500 vs 100 = +1400%)", !!wk2.menuRisers.find((m) => m.name === "ปีกไก่" && near(m.deltaPct ?? 0, 1400)));

  const wd = analytics.weekdayStats(bid, "2026-09-20", 56);
  ok("weekday stats Mon-first, 7 entries", wd.length === 7 && wd[0].label === "จันทร์");
  ok("weekday Monday avg = 10000 (only 09-14)", near(wd[0].avgNett, 10000) && wd[0].days === 1);

  const di = analytics.discountInsight(bid, 2026, 9);
  ok("discount insight has days", di.days === 4 && di.totalDiscount > 0);

  const cm = analytics.monthChannelMix(bid2, 2026, 9);
  ok("channel mix empty types when none", cm.types.length === 0);
  // channel avg-ticket on bid (has QR/TAKEAWAY types on 09-16 via close_up parse? no — bid types are [])
  ok("channel avgTicket null when qty 0", cm.types.every((t) => t.avgTicket === null || t.avgTicket! >= 0));

  // Deeper insights (owner 2026-09-18) on bid2 (Sept: 09-09 nett13000, 09-16 nett14658).
  const me = analytics.menuEngineering(bid, 2026, 9);
  ok("menuEngineering returns 4 buckets + has items", Array.isArray(me.stars) && (me.stars.length + me.plowhorses.length + me.puzzles.length + me.dogs.length) > 0);
  const conc = analytics.menuConcentration(bid, 2026, 9);
  ok("concentration top5 ≤ 100% + countFor80 ≥ 1", conc.top5Pct != null && conc.top5Pct <= 100.01 && conc.countFor80 >= 1);
  const gm = analytics.guestMetrics(bid2, 2026, 9);
  // Sept bid2: nett 27658, bills (23+21)=44... actually 09-16 bills 23, 09-09 bills 21 → 44; pax 43+40=83.
  ok("guest party size = pax/bills", gm.avgPartySize != null && near(gm.avgPartySize, 83 / 44));
  ok("guest spend/head = nett/pax", gm.avgSpendPerHead != null && near(gm.avgSpendPerHead, 27658 / 83));
  const rh = analytics.rhythmInsight(bid2, 2026, 9);
  ok("rhythm payday split present", rh.paydayDays >= 0);
  const bv = analytics.beverageMix(bid2, 2026, 9);
  ok("beverage mix shares sum ~100 when total>0", bv.total === 0 || near(bv.foodPct + bv.beveragePct + bv.dessertPct, 100));
  const q = analytics.qualitySignal(bid2, 2026, 9);
  ok("quality void rate computed (0 here)", q.voidRatePct != null && q.voidRatePct >= 0);

  // ── 7) C target progress · F monthly card ──
  const mo = analytics.monthlyAnalytics(bid2, 2026, 9);
  ok("monthly total (14658+13000)", mo.totalNett === 27658 && mo.dayCount === 2);
  ok("monthly vs prev month (Aug 14000)", near(mo.prevMonthPct ?? 0, ((27658 - 14000) / 14000) * 100));
  ok("monthly vs last year (2025-09 50000)", near(mo.lastYearPct ?? 0, ((27658 - 50000) / 50000) * 100));
  ok("monthly label full Thai", mo.label === "กันยายน 2569" && mo.ym === "2026-09");

  const tp = analytics.targetProgress(60000, 30000, 15, 2026, 9)!;
  ok("target pctOfTarget 50%", near(tp.pctOfTarget, 50));
  ok("target projection 30000/15*30=60000", near(tp.projectedNett, 60000) && tp.onTrack === true);
  ok("targetProgress null when target<=0", analytics.targetProgress(0, 100, 5, 2026, 9) === null);

  ok("monthly target setting round-trip", (() => {
    sdb.setMonthlyTarget(bid2, 500000);
    const got = sdb.getMonthlyTarget(bid2) === 500000;
    sdb.setMonthlyTarget(bid2, null);
    return got && sdb.getMonthlyTarget(bid2) === null;
  })());
  ok("monthly sent round-trip", (() => {
    sdb.markMonthlySent(bid2, "2026-09", uid);
    return sdb.monthlySentAt(bid2, "2026-09") != null;
  })());
  ok("merchant name round-trip + clear", (() => {
    sdb.setMerchantName(bid2, "  HYPOPLARAEMIA  ");
    const got = sdb.getMerchantName(bid2) === "HYPOPLARAEMIA";
    sdb.setMerchantName(bid2, "");
    return got && sdb.getMerchantName(bid2) === null;
  })());
  ok("listDayMerchants returns per-day merchant (for wrong-shop cleanup)", (() => {
    const rows = sdb.listDayMerchants(bid2);
    return rows.length > 0 && rows.every((r) => r.merchant === "R2");
  })());
  ok("card colour: valid hex stored, invalid rejected", (() => {
    sdb.setCardColor(bid2, "#1E3A5F");
    const good = sdb.getCardColor(bid2) === "#1e3a5f";
    sdb.setCardColor(bid2, "not-a-color");
    const rejected = sdb.getCardColor(bid2) === null;
    return good && rejected;
  })());

  // ── 8) Receipt DB + insights (hourly / units / basket, excl STAFF) ──
  const bid4 = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('r4','REST4')").run().lastInsertRowid);
  const rbuf2 = receiptBuf("17/09/2026", "R4", [
    { time: "17/09/2026 12:07:20", no: "1", table: "G2", gross: "1000", discount: "-100", nett: "1000", payment: "PromptPay", items: "1x A,1x B,2x C" },
    { time: "17/09/2026 12:40:00", no: "2", table: "S4", gross: "600", discount: "0", nett: "600", payment: "PromptPay", items: "1x A,1x C" },
    { time: "17/09/2026 19:30:00", no: "3", table: "C2", gross: "800", discount: "0", nett: "800", payment: "PromptPay", items: "1x A,1x B" },
    { time: "17/09/2026 20:00:00", no: "4", table: "STAFF", gross: "300", discount: "-300", nett: "0", payment: "", items: "5x A,5x B" }
  ]);
  const rParsed = parse.parseSalesFile(rbuf2);
  if (rParsed.kind === "receipt") sdb.upsertReceipts(bid4, uid, rParsed.receipt);
  ok("upsertReceipts sets has_receipt", sdb.getDaily(bid4, "2026-09-17")?.has_receipt === 1);
  const ri = analytics.receiptInsights(bid4, 2026, 9);
  ok("receipt hasData + peak hour 12 (1600>800)", ri.hasData && ri.peakHour === 12);
  ok("hourly 12:00 has 2 bills", ri.hourly.find((h) => h.hour === 12)?.bills === 2);
  // Item units excl staff: A=1+1+1=3, B=1+1=2, C=2+1=3 (staff A/B not counted)
  ok("item units exclude staff (A=3)", ri.topUnits.find((u) => u.name === "A")?.units === 3);
  ok("item units B=2 (staff 5 excluded)", ri.topUnits.find((u) => u.name === "B")?.units === 2);
  // Basket: A+B appears in bills 1,3 = 2; A+C in bills 1,2 = 2 (staff excluded)
  ok("basket pair A+B count 2", !!ri.basket.find((p) => (p.a === "A" && p.b === "B") && p.count === 2));
  ok("clearDay removes receipts too", (() => { sdb.clearDay(bid4, "2026-09-17"); return !analytics.receiptInsights(bid4, 2026, 9).hasData; })());

  console.log(`\n${failed === 0 ? "✓ ALL PASS" : "✗ FAILURES"} — ${passed} passed, ${failed} failed`);
  cleanup();
  process.exit(failed === 0 ? 0 : 1);
})();
