// SALESA proof — POS file parsers + DB upsert + daily/weekly analytics.
//
// Self-contained: builds throwaway .xlsx buffers shaped like the FeedMe
// "Close up" (KPI) and "Overview" (menu-revenue) exports, then a throwaway DB
// with one branch, and proves:
//   • parseCloseUp reads the aggregate KPIs (Nett/bills/discount/payments/types)
//   • parseOverview ranks categories + individual menus by revenue (desc)
//   • upsert + dailyAnalytics (discount %, prev-day + 7-day compare, top/bottom)
//   • weeklyAnalytics (Mon–Sun total, best day, menu aggregation across days)
//   • clearDay removes a day
//
// Run:  node --import tsx scripts/test-salesa.ts   (or: npm run test:salesa)

import fs from "node:fs";
import path from "node:path";
import * as XLSX from "xlsx";

const TMP = path.join(process.cwd(), "data", "test-salesa.db");
function cleanup() {
  for (const f of [TMP, `${TMP}-wal`, `${TMP}-shm`]) {
    try { fs.rmSync(f, { force: true }); } catch { /* ignore */ }
  }
}
cleanup();
fs.mkdirSync(path.dirname(TMP), { recursive: true });
process.env.DATABASE_PATH = TMP;

// ── Build a workbook buffer from { sheetName: rows } ──
function wbBuf(sheets: Record<string, unknown[][]>): Buffer {
  const wb = XLSX.utils.book_new();
  for (const [name, rows] of Object.entries(sheets)) {
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(rows), name.slice(0, 31));
  }
  return XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
}
function preamble(title: string, date: string, merchant: string): unknown[][] {
  return [[title], [`Date: ${date} - ${date}`], ["Time: 00:00 - 23:59"], [`Merchant: ${merchant}`], ["Generated by: test"], []];
}
/** A "Name/Value" scalar sheet. */
function scalar(title: string, date: string, merchant: string, name: string, value: string): unknown[][] {
  return [...preamble(title, date, merchant), ["Name", "Value"], [name, value]];
}

function closeUpBuf(date: string, merchant: string): Buffer {
  const P = (label: string, val: string) => scalar("Close up", date, merchant, label, val);
  return wbBuf({
    "1.Bill count": P("Bill count", "23"),
    "2.Total Sales": P("Total Sales", "14,658"),
    "3.Total Pax": P("Total Pax", "43"),
    "4.Total Discount": P("Total Discount", "-2,105"),
    "8.Average Sales": P("Average Sales", "666.27"),
    "9.Average Pax": P("Average Pax", "1.95"),
    "10.Average Sales Pax": P("Average Sales Pax", "340.88"),
    "11.Payment summary": [...preamble("Close up", date, merchant), ["Name", "Refund", "Qty", "Total"], ["PromptPay", "No", "20", "13,245"], ["Mastercard Credit card", "No", "1", "1,413"]],
    "15.Type summary": [...preamble("Close up", date, merchant), ["Type", "Qty", "Sales"], ["QR", "15", "13,560"], ["TAKEAWAY", "7", "1,098"], ["DINE IN", "1", "0"]],
    "18.Sales summary": [...preamble("Close up", date, merchant), ["Label", "Value"], ["Gross", "15,201"], ["Discount", "-2,105"], ["Gross before charges", "13,096"], ["Service charge", "603.46"], ["VAT", "958.97"], ["Rounding", "-0.43"], ["Nett", "14,658"]]
  });
}
function overviewBuf(date: string, merchant: string, items: Array<[string, string]>, cats: Array<[string, string]>): Buffer {
  const catHeader = ["Dataset", ...cats.map((c) => c[0])];
  const catNett = ["Nett", ...cats.map((c) => c[1])];
  return wbBuf({
    "1.Top products": [...preamble("Overview", date, merchant), catHeader, catNett],
    "4.Top products": [...preamble("Overview", date, merchant), ["Name", "Value"], ...items]
  });
}

(async () => {
  const parse = await import("../src/lib/salesa-parse");
  const { getDb } = await import("../src/lib/db");
  const sdb = await import("../src/lib/salesa-db");
  const analytics = await import("../src/lib/salesa-analytics");

  let passed = 0, failed = 0;
  const ok = (name: string, cond: boolean) => {
    if (cond) { passed++; console.log(`  ✓ ${name}`); }
    else { failed++; console.error(`  ✗ FAIL: ${name}`); }
  };
  const near = (a: number, b: number) => Math.abs(a - b) < 0.01;

  // ── 1) parseCloseUp ──
  const cu = parse.parseCloseUp(closeUpBuf("16/09/2026", "TESTBR"));
  ok("close_up date CE", cu.date === "2026-09-16");
  ok("close_up merchant", cu.merchant === "TESTBR");
  ok("close_up nett", cu.nett === 14658);
  ok("close_up gross", cu.gross === 15201);
  ok("close_up discount negative", cu.discount === -2105);
  ok("close_up vat", near(cu.vat, 958.97));
  ok("close_up bill count", cu.billCount === 23);
  ok("close_up pax", cu.pax === 43);
  ok("close_up avg per head", near(cu.avgSalesPax, 340.88));
  ok("close_up payments parsed", cu.payments.length === 2 && cu.payments.some((p) => p.name === "PromptPay" && p.total === 13245));
  ok("close_up types parsed", cu.types.find((t) => t.name === "QR")?.sales === 13560);
  ok("isCloseUp true / isOverview false", parse.isCloseUp(closeUpBuf("16/09/2026", "X")) && !parse.isOverview(closeUpBuf("16/09/2026", "X")));

  // ── 2) parseOverview (ranked desc) ──
  const ov = parse.parseOverview(overviewBuf("16/09/2026", "TESTBR",
    [["คอหมูย่าง", "1206.14"], ["เนื้อพิคันย่างถ่าน", "1613.8"], ["ยำมาม่า", "782.63"]],
    [["ส้มตำ", "2561.63"], ["ย่าง", "2819.93"]]));
  ok("overview items sorted desc", ov.items[0].name === "เนื้อพิคันย่างถ่าน" && ov.items[0].nett === 1613.8);
  ok("overview items tail lowest", ov.items[ov.items.length - 1].name === "ยำมาม่า");
  ok("overview categories sorted desc", ov.categories[0].name === "ย่าง" && ov.categories[0].nett === 2819.93);
  ok("parseSalesFile dispatch", parse.parseSalesFile(overviewBuf("16/09/2026", "X", [["a", "10"]], [["b", "20"]])).kind === "overview");

  // ── 3) DB + analytics ──
  const db = getDb();
  const bid = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('r','REST')").run().lastInsertRowid);
  const uid = Number(db.prepare("INSERT INTO users (username,password_hash,display_name,role,status) VALUES ('op','x','ผู้จัดการ','admin','active')").run().lastInsertRowid);

  // A full ISO week: Mon 2026-09-14 … Sun 2026-09-20. Vary the netts.
  const week: Array<{ d: string; nett: number; bills: number; pax: number }> = [
    { d: "2026-09-14", nett: 10000, bills: 20, pax: 30 },
    { d: "2026-09-15", nett: 12000, bills: 22, pax: 35 },
    { d: "2026-09-16", nett: 14658, bills: 23, pax: 43 },
    { d: "2026-09-17", nett: 9000, bills: 18, pax: 25 },
    { d: "2026-09-18", nett: 20000, bills: 30, pax: 55 },
  ];
  for (const w of week) {
    sdb.upsertDaily(bid, uid, {
      date: w.d, dateEnd: w.d, merchant: "REST", nett: w.nett, gross: w.nett + 500, grossBeforeCharges: w.nett - 1000,
      discount: -500, serviceCharge: 100, vat: 200, rounding: 0, deliveryFee: 0, otherCharge: 0,
      billCount: w.bills, pax: w.pax, voidAmount: 0, voidBillCount: 0, refund: 0,
      avgSales: Math.round(w.nett / w.bills), avgPax: w.pax / w.bills, avgSalesPax: Math.round(w.nett / w.pax),
      payments: [{ name: "PromptPay", qty: w.bills, total: w.nett }], types: [], sources: []
    });
  }
  // Menu for two days (aggregation test).
  sdb.upsertMenu(bid, uid, { date: "2026-09-16", dateEnd: "2026-09-16", merchant: "REST",
    categories: [{ name: "ย่าง", nett: 2000 }], items: [
      { name: "คอหมูย่าง", nett: 1200 }, { name: "ปีกไก่", nett: 900 }, { name: "ยำมาม่า", nett: 700 },
      { name: "ลาบ", nett: 500 }, { name: "ต้มแซ่บ", nett: 300 }, { name: "ข้าวเหนียว", nett: 100 }
    ] });
  sdb.upsertMenu(bid, uid, { date: "2026-09-18", dateEnd: "2026-09-18", merchant: "REST",
    categories: [{ name: "ย่าง", nett: 1500 }], items: [{ name: "คอหมูย่าง", nett: 800 }, { name: "ปีกไก่", nett: 600 }] });

  ok("upsert idempotent (re-import same day → still 5 rows)", (() => {
    sdb.upsertDaily(bid, uid, { date: "2026-09-16", dateEnd: "2026-09-16", merchant: "REST", nett: 14658, gross: 15201, grossBeforeCharges: 13096, discount: -2105, serviceCharge: 603.46, vat: 958.97, rounding: -0.43, deliveryFee: 0, otherCharge: 0, billCount: 23, pax: 43, voidAmount: 90, voidBillCount: 1, refund: 0, avgSales: 666.27, avgPax: 1.95, avgSalesPax: 340.88, payments: [], types: [], sources: [] });
    return sdb.listMonth(bid, 2026, 9).length === 5;
  })());

  const a16 = analytics.dailyAnalytics(bid, "2026-09-16")!;
  ok("daily discountPct = |−2105|/15201", near(a16.discountPct ?? 0, (2105 / 15201) * 100));
  ok("daily prev day = 09-15", a16.prevDate === "2026-09-15");
  ok("daily vs prev = (14658−12000)/12000", near(a16.nettVsPrevPct ?? 0, ((14658 - 12000) / 12000) * 100));
  ok("daily 7-day avg over 2 prior days", a16.avg7Days === 2 && near(a16.avg7Nett ?? 0, (10000 + 12000) / 2));
  ok("daily metrics has 5 headings", a16.metrics.length === 5 && a16.metrics.map((m) => m.key).join(",") === "nett,bills,pax,avgBill,avgHead");
  const bills = a16.metrics.find((m) => m.key === "bills")!;
  ok("bills prevPct = (23−22)/22", near(bills.prevPct ?? 0, ((23 - 22) / 22) * 100));
  ok("bills avgPct vs 2-day avg (20,22)→21", near(bills.avgPct ?? 0, ((23 - 21) / 21) * 100));
  const pax = a16.metrics.find((m) => m.key === "pax")!;
  ok("pax prevPct = (43−35)/35", near(pax.prevPct ?? 0, ((43 - 35) / 35) * 100));
  ok("daily top item = คอหมูย่าง", a16.topItems[0]?.name === "คอหมูย่าง");
  ok("daily bottom item = ข้าวเหนียว (lowest)", a16.bottomItems[0]?.name === "ข้าวเหนียว");

  const wk = analytics.weeklyAnalytics(bid, "2026-09-16");
  ok("weekly Monday anchor", wk.weekStart === "2026-09-14" && wk.weekEnd === "2026-09-20");
  ok("weekly total = sum of 5 days", wk.totalNett === 10000 + 12000 + 14658 + 9000 + 20000);
  ok("weekly best day = 09-18", wk.bestDate === "2026-09-18" && wk.bestNett === 20000);
  ok("weekly bills summed", wk.totalBills === 20 + 22 + 23 + 18 + 30);
  ok("weekly menu aggregated across days (คอหมูย่าง 1200+800)", wk.topItems.find((i) => i.name === "คอหมูย่าง")?.nett === 2000);
  ok("weekly avgPerBill = total/bills", near(wk.avgPerBill ?? 0, wk.totalNett / wk.totalBills));

  // ── 4) clearDay ──
  ok("clearDay removes the day", (() => {
    sdb.clearDay(bid, "2026-09-17");
    return sdb.getDaily(bid, "2026-09-17") === null && sdb.listMonth(bid, 2026, 9).length === 4;
  })());
  ok("settings round-trip", (() => {
    sdb.setLineGroupId(bid, "  Cabc123  ");
    return sdb.getLineGroupId(bid) === "Cabc123";
  })());

  console.log(`\n${failed === 0 ? "✓ ALL PASS" : "✗ FAILURES"} — ${passed} passed, ${failed} failed`);
  cleanup();
  process.exit(failed === 0 ? 0 : 1);
})();
