// SALESA proof — POS file parsers + DB upsert + daily/weekly analytics.
//
// Self-contained: builds throwaway .xlsx buffers shaped like the FeedMe
// "Close up" (KPI) and "Overview" (menu-revenue) exports, then a throwaway DB
// with one branch, and proves:
//   • parseCloseUp reads the aggregate KPIs (Nett/bills/discount/payments/types)
//   • parseOverview ranks categories + individual menus by revenue (desc)
//   • upsert + dailyAnalytics (discount %, prev-day + 7-day compare, top/bottom)
//   • weeklyAnalytics (Mon–Sun total, best day, menu aggregation across days)
//   • clearDay removes a day
//
// Run:  node --import tsx scripts/test-salesa.ts   (or: npm run test:salesa)

import fs from "node:fs";
import path from "node:path";
import * as XLSX from "xlsx";

const TMP = path.join(process.cwd(), "data", "test-salesa.db");
function cleanup() {
  for (const f of [TMP, `${TMP}-wal`, `${TMP}-shm`]) {
    try { fs.rmSync(f, { force: true }); } catch { /* ignore */ }
  }
}
cleanup();
fs.mkdirSync(path.dirname(TMP), { recursive: true });
process.env.DATABASE_PATH = TMP;

// ── Build a workbook buffer from { sheetName: rows } ──
function wbBuf(sheets: Record<string, unknown[][]>): Buffer {
  const wb = XLSX.utils.book_new();
  for (const [name, rows] of Object.entries(sheets)) {
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(rows), name.slice(0, 31));
  }
  return XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
}
function preamble(title: string, date: string, merchant: string): unknown[][] {
  return [[title], [`Date: ${date} - ${date}`], ["Time: 00:00 - 23:59"], [`Merchant: ${merchant}`], ["Generated by: test"], []];
}
/** A "Name/Value" scalar sheet. */
function scalar(title: string, date: string, merchant: string, name: string, value: string): unknown[][] {
  return [...preamble(title, date, merchant), ["Name", "Value"], [name, value]];
}

function receiptBuf(date: string, merchant: string, bills: Array<{ time: string; no: string; table: string; gross: string; discount: string; nett: string; payment: string; items: string }>): Buffer {
  const header = ["Time", "No.", "Table", "Status", "ID", "Gross", "Discount", "VAT", "SC", "Other Charge", "Delivery fee", "Rounding", "Nett", "Payment", "Items"];
  const rows = bills.map((b) => [b.time, b.no, b.table, "COMPLETED", "id", b.gross, b.discount, "0", "0", "0", "0", "0", b.nett, b.payment, b.items]);
  return wbBuf({ "1.": [...preamble("Receipt", date, merchant), header, ...rows] });
}

function closeUpBuf(date: string, merchant: string): Buffer {
  const P = (label: string, val: string) => scalar("Close up", date, merchant, label, val);
  return wbBuf({
    "1.Bill count": P("Bill count", "23"),
    "2.Total Sales": P("Total Sales", "14,658"),
    "3.Total Pax": P("Total Pax", "43"),
    "4.Total Discount": P("Total Discount", "-2,105"),
    "8.Average Sales": P("Average Sales", "666.27"),
    "9.Average Pax": P("Average Pax", "1.95"),
    "10.Average Sales Pax": P("Average Sales Pax", "340.88"),
    "11.Payment summary": [...preamble("Close up", date, merchant), ["Name", "Refund", "Qty", "Total"], ["PromptPay", "No", "20", "13,245"], ["Mastercard Credit card", "No", "1", "1,413"]],
    "15.Type summary": [...preamble("Close up", date, merchant), ["Type", "Qty", "Sales"], ["QR", "15", "13,560"], ["TAKEAWAY", "7", "1,098"], ["DINE IN", "1", "0"]],
    "18.Sales summary": [...preamble("Close up", date, merchant), ["Label", "Value"], ["Gross", "15,201"], ["Discount", "-2,105"], ["Gross before charges", "13,096"], ["Service charge", "603.46"], ["VAT", "958.97"], ["Rounding", "-0.43"], ["Nett", "14,658"]]
  });
}
function overviewBuf(date: string, merchant: string, items: Array<[string, string]>, cats: Array<[string, string]>): Buffer {
  const catHeader = ["Dataset", ...cats.map((c) => c[0])];
  const catNett = ["Nett", ...cats.map((c) => c[1])];
  return wbBuf({
    "1.Top products": [...preamble("Overview", date, merchant), catHeader, catNett],
    "4.Top products": [...preamble("Overview", date, merchant), ["Name", "Value"], ...items]
  });
}

(async () => {
  const parse = await import("../src/lib/salesa-parse");
  const { getDb } = await import("../src/lib/db");
  const sdb = await import("../src/lib/salesa-db");
  const analytics = await import("../src/lib/salesa-analytics");
  const push = await import("../src/lib/salesa-push");

  let passed = 0, failed = 0;
  const ok = (name: string, cond: boolean) => {
    if (cond) { passed++; console.log(`  ✓ ${name}`); }
    else { failed++; console.error(`  ✗ FAIL: ${name}`); }
  };
  const near = (a: number, b: number) => Math.abs(a - b) < 0.01;

  // ── 1) parseCloseUp ──
  const cu = parse.parseCloseUp(closeUpBuf("16/09/2026", "TESTBR"));
  ok("close_up date CE", cu.date === "2026-09-16");
  ok("close_up merchant", cu.merchant === "TESTBR");
  ok("close_up nett", cu.nett === 14658);
  ok("close_up gross", cu.gross === 15201);
  ok("close_up discount negative", cu.discount === -2105);
  ok("close_up vat", near(cu.vat, 958.97));
  ok("close_up bill count", cu.billCount === 23);
  ok("close_up pax", cu.pax === 43);
  ok("close_up avg per head", near(cu.avgSalesPax, 340.88));
  ok("close_up payments parsed", cu.payments.length === 2 && cu.payments.some((p) => p.name === "PromptPay" && p.total === 13245));
  ok("close_up types parsed", cu.types.find((t) => t.name === "QR")?.sales === 13560);
  ok("isCloseUp true / isOverview false", parse.isCloseUp(closeUpBuf("16/09/2026", "X")) && !parse.isOverview(closeUpBuf("16/09/2026", "X")));

  // ── 2) parseOverview (ranked desc) ──
  const ov = parse.parseOverview(overviewBuf("16/09/2026", "TESTBR",
    [["คอหมูย่าง", "1206.14"], ["เนื้อพิคันย่างถ่าน", "1613.8"], ["ยำมาม่า", "782.63"]],
    [["ส้มตำ", "2561.63"], ["ย่าง", "2819.93"]]));
  ok("overview items sorted desc", ov.items[0].name === "เนื้อพิคันย่างถ่าน" && ov.items[0].nett === 1613.8);
  ok("overview items tail lowest", ov.items[ov.items.length - 1].name === "ยำมาม่า");
  ok("overview categories sorted desc", ov.categories[0].name === "ย่าง" && ov.categories[0].nett === 2819.93);
  ok("parseSalesFile dispatch", parse.parseSalesFile(overviewBuf("16/09/2026", "X", [["a", "10"]], [["b", "20"]])).kind === "overview");

  // Duplicate item/category name (some POS "Top products" exports repeat a row)
  // → merged + summed so upsertMenu doesn't clash on the PK (owner 2026-09-20).
  const ovDup = parse.parseOverview(overviewBuf("16/09/2026", "TESTBR",
    [["คอหมูย่าง", "1000"], ["เนื้อย่าง", "600"], ["คอหมูย่าง", "500"]],
    [["ย่าง", "2000"], ["ส้มตำ", "300"], ["ย่าง", "100"]]));
  ok("overview merges duplicate item name (1000+500=1500)",
    ovDup.items.filter((i) => i.name === "คอหมูย่าง").length === 1 &&
    ovDup.items.find((i) => i.name === "คอหมูย่าง")?.nett === 1500 &&
    ovDup.items[0].name === "คอหมูย่าง");
  ok("overview merges duplicate category name (2000+100=2100)",
    ovDup.categories.filter((c) => c.name === "ย่าง").length === 1 &&
    ovDup.categories.find((c) => c.name === "ย่าง")?.nett === 2100);

  // ── receipt parser ──
  const rbuf = receiptBuf("17/09/2026", "TESTBR", [
    { time: "17/09/2026 12:07:20", no: "1", table: "G2", gross: "1,000", discount: "-100", nett: "1,000", payment: "PromptPay", items: "1x ข้าวสวย,1x คอหมูย่าง,2x ข้าวเหนียว" },
    { time: "17/09/2026 19:30:00", no: "2", table: "C2", gross: "500", discount: "-50", nett: "500", payment: "PromptPay", items: "1x คอหมูย่าง,1x ข้าวเหนียว\t\t, 1x  โค้ก " },
    { time: "17/09/2026 20:00:00", no: "3", table: "STAFF", gross: "300", discount: "-300", nett: "0", payment: "", items: "1x ข้าวสวย,1x ปลาทู" }
  ]);
  const rp = parse.parseSalesFile(rbuf);
  ok("receipt kind + date + merchant", rp.kind === "receipt" && rp.kind === "receipt" && rp.receipt.date === "2026-09-17" && rp.receipt.merchant === "TESTBR");
  if (rp.kind === "receipt") {
    ok("receipt bills parsed (3)", rp.receipt.bills.length === 3);
    const b1 = rp.receipt.bills[0];
    ok("receipt hour + qty aggregation", b1.hour === 12 && b1.items.find((i) => i.name === "ข้าวเหนียว")?.qty === 2);
    ok("receipt name cleaning (tabs/spaces)", !!rp.receipt.bills[1].items.find((i) => i.name === "โค้ก") && !!rp.receipt.bills[1].items.find((i) => i.name === "ข้าวเหนียว"));
    ok("receipt staff flagged", rp.receipt.bills[2].isStaff === true && rp.receipt.bills[0].isStaff === false);
  }

  // ── 3) DB + analytics ──
  const db = getDb();
  const bid = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('r','REST')").run().lastInsertRowid);
  const uid = Number(db.prepare("INSERT INTO users (username,password_hash,display_name,role,status) VALUES ('op','x','ผู้จัดการ','admin','active')").run().lastInsertRowid);

  // upsertMenu ON CONFLICT safety net: a raw list with a duplicate name (past the
  // parser merge) must sum, not crash on the PK (owner 2026-09-20).
  ok("upsertMenu sums duplicate item names without PK crash", (() => {
    const b = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('dupmenu','DUPM')").run().lastInsertRowid);
    try {
      sdb.upsertMenu(b, uid, { date: "2026-09-16", dateEnd: "2026-09-16", merchant: "DUPM", categories: [],
        items: [{ name: "คอหมูย่าง", nett: 1000 }, { name: "เนื้อย่าง", nett: 600 }, { name: "คอหมูย่าง", nett: 500 }] });
    } catch { return false; }
    const row = db.prepare("SELECT nett FROM salesa_menu WHERE branch_id=? AND kind='item' AND name='คอหมูย่าง'").get(b) as { nett: number } | undefined;
    return !!row && Math.abs(row.nett - 1500) < 0.01;
  })());

  // A full ISO week: Mon 2026-09-14 … Sun 2026-09-20. Vary the netts.
  const week: Array<{ d: string; nett: number; bills: number; pax: number }> = [
    { d: "2026-09-14", nett: 10000, bills: 20, pax: 30 },
    { d: "2026-09-15", nett: 12000, bills: 22, pax: 35 },
    { d: "2026-09-16", nett: 14658, bills: 23, pax: 43 },
    { d: "2026-09-17", nett: 9000, bills: 18, pax: 25 },
    { d: "2026-09-18", nett: 20000, bills: 30, pax: 55 },
  ];
  for (const w of week) {
    sdb.upsertDaily(bid, uid, {
      date: w.d, dateEnd: w.d, merchant: "REST", nett: w.nett, gross: w.nett + 500, grossBeforeCharges: w.nett - 1000,
      discount: -500, serviceCharge: 100, vat: 200, rounding: 0, deliveryFee: 0, otherCharge: 0,
      billCount: w.bills, pax: w.pax, voidAmount: 0, voidBillCount: 0, refund: 0,
      avgSales: Math.round(w.nett / w.bills), avgPax: w.pax / w.bills, avgSalesPax: Math.round(w.nett / w.pax),
      payments: [{ name: "PromptPay", qty: w.bills, total: w.nett }], types: [], sources: []
    });
  }
  // Menu for two days (aggregation test).
  sdb.upsertMenu(bid, uid, { date: "2026-09-16", dateEnd: "2026-09-16", merchant: "REST",
    categories: [{ name: "ย่าง", nett: 2000 }], items: [
      { name: "คอหมูย่าง", nett: 1200 }, { name: "ปีกไก่", nett: 900 }, { name: "ยำมาม่า", nett: 700 },
      { name: "ลาบ", nett: 500 }, { name: "ต้มแซ่บ", nett: 300 }, { name: "ข้าวเหนียว", nett: 100 }
    ] });
  sdb.upsertMenu(bid, uid, { date: "2026-09-18", dateEnd: "2026-09-18", merchant: "REST",
    categories: [{ name: "ย่าง", nett: 1500 }], items: [{ name: "คอหมูย่าง", nett: 800 }, { name: "ปีกไก่", nett: 600 }] });

  ok("upsert idempotent (re-import same day → still 5 rows)", (() => {
    sdb.upsertDaily(bid, uid, { date: "2026-09-16", dateEnd: "2026-09-16", merchant: "REST", nett: 14658, gross: 15201, grossBeforeCharges: 13096, discount: -2105, serviceCharge: 603.46, vat: 958.97, rounding: -0.43, deliveryFee: 0, otherCharge: 0, billCount: 23, pax: 43, voidAmount: 90, voidBillCount: 1, refund: 0, avgSales: 666.27, avgPax: 1.95, avgSalesPax: 340.88, payments: [], types: [], sources: [] });
    return sdb.listMonth(bid, 2026, 9).length === 5;
  })());

  const a16 = analytics.dailyAnalytics(bid, "2026-09-16")!;
  ok("daily discountPct = |−2105|/15201", near(a16.discountPct ?? 0, (2105 / 15201) * 100));
  ok("daily metrics has 5 headings", a16.metrics.length === 5 && a16.metrics.map((m) => m.key).join(",") === "nett,bills,pax,avgBill,avgHead");
  ok("no WoW/MoM baseline → null (this dataset)", a16.metrics.every((m) => m.wowPct === null && m.momPct === null));
  ok("weekday/dom labels", a16.weekdayTh === "พุธ" && a16.wowLabel === "วันพุธที่แล้ว" && a16.momLabel === "สะสม 16 วันแรก · เดือนก่อน");
  ok("daily top item = คอหมูย่าง", a16.topItems[0]?.name === "คอหมูย่าง");
  ok("daily bottom item = ข้าวเหนียว (lowest)", a16.bottomItems[0]?.name === "ข้าวเหนียว");
  // advice: discount ~13.8% (≥8 → warning) + top-earning menu highlight; no
  // WoW/MoM baseline in this dataset so no trend headline.
  ok("advice flags high discount", a16.advice.some((l) => l.includes("ส่วนลดสูง")));
  ok("advice highlights top menu", a16.advice.some((l) => l.includes("คอหมูย่าง")));
  ok("advice capped at 4 lines", a16.advice.length <= 4);

  const wk = analytics.weeklyAnalytics(bid, "2026-09-16");
  ok("weekly Monday anchor", wk.weekStart === "2026-09-14" && wk.weekEnd === "2026-09-20");
  ok("weekly total = sum of 5 days", wk.totalNett === 10000 + 12000 + 14658 + 9000 + 20000);
  ok("weekly best day = 09-18", wk.bestDate === "2026-09-18" && wk.bestNett === 20000);
  ok("weekly bills summed", wk.totalBills === 20 + 22 + 23 + 18 + 30);
  ok("weekly menu aggregated across days (คอหมูย่าง 1200+800)", wk.topItems.find((i) => i.name === "คอหมูย่าง")?.nett === 2000);
  ok("weekly avgPerBill = total/bills", near(wk.avgPerBill ?? 0, wk.totalNett / wk.totalBills));
  ok("weekly WoW null with no prior week (this dataset)", wk.prevWeekNett === null && wk.wowNettPct === null);
  // Fresh branch: clean two adjacent ISO weeks for a WoW check.
  const bid3 = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('r3','REST3')").run().lastInsertRowid);
  const put3 = (d: string, nett: number, bills: number, pax: number) => sdb.upsertDaily(bid3, uid, { date: d, dateEnd: d, merchant: "R3", nett, gross: nett, grossBeforeCharges: nett, discount: 0, serviceCharge: 0, vat: 0, rounding: 0, deliveryFee: 0, otherCharge: 0, billCount: bills, pax, voidAmount: 0, voidBillCount: 0, refund: 0, avgSales: nett / bills, avgPax: pax / bills, avgSalesPax: nett / pax, payments: [], types: [], sources: [] });
  put3("2026-09-08", 100000, 100, 150);  // prev week (09-07..13)
  put3("2026-09-15", 120000, 110, 160);  // this week (09-14..20)
  const wkc = analytics.weeklyAnalytics(bid3, "2026-09-15");
  ok("weekly WoW nett (120000 vs 100000 = +20%)", near(wkc.wowNettPct ?? 0, 20) && wkc.prevWeekNett === 100000);
  ok("weekly WoW bills (110 vs 100 = +10%)", near(wkc.wowBillsPct ?? 0, 10));

  // ── 4) clearDay ──
  ok("clearDay removes the day", (() => {
    sdb.clearDay(bid, "2026-09-17");
    return sdb.getDaily(bid, "2026-09-17") === null && sdb.listMonth(bid, 2026, 9).length === 4;
  })());
  ok("settings round-trip", (() => {
    sdb.setLineGroupId(bid, "  Cabc123  ");
    return sdb.getLineGroupId(bid) === "Cabc123";
  })());

  // ── 5) WoW / MoM / month comparisons on an isolated branch ──
  const bid2 = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('r2','REST2')").run().lastInsertRowid);
  const put = (d: string, nett: number, bills: number, pax: number) => sdb.upsertDaily(bid2, uid, {
    date: d, dateEnd: d, merchant: "R2", nett, gross: nett, grossBeforeCharges: nett, discount: 0,
    serviceCharge: 0, vat: 0, rounding: 0, deliveryFee: 0, otherCharge: 0, billCount: bills, pax,
    voidAmount: 0, voidBillCount: 0, refund: 0, avgSales: nett / bills, avgPax: pax / bills,
    avgSalesPax: nett / pax, payments: [], types: [], sources: []
  });
  put("2026-09-16", 14658, 23, 43);   // target (Wed) — MTD 1..16 this month
  put("2026-09-09", 13000, 21, 40);   // same weekday last week (also in MTD)
  put("2026-08-16", 14000, 24, 45);   // last month's 1..16 window (only day)
  put("2025-09-05", 50000, 80, 150);  // last year, same month (for YoY MTD)

  const a2 = analytics.dailyAnalytics(bid2, "2026-09-16")!;
  const bills2 = a2.metrics.find((m) => m.key === "bills")!;
  const pax2 = a2.metrics.find((m) => m.key === "pax")!;
  ok("WoW bills vs วันพุธที่แล้ว (23 vs 21)", near(bills2.wowPct ?? 0, ((23 - 21) / 21) * 100));
  // MoM now compares cumulative 1–16: this month bills 23+21=44 vs last month 24.
  ok("MoM bills cumulative 1–16 (44 vs 24)", near(bills2.momPct ?? 0, ((44 - 24) / 24) * 100));
  ok("WoW pax (43 vs 40)", near(pax2.wowPct ?? 0, ((43 - 40) / 40) * 100));
  // pax cumulative 1–16: 43+40=83 vs 45.
  ok("MoM pax cumulative 1–16 (83 vs 45)", near(pax2.momPct ?? 0, ((83 - 45) / 45) * 100));
  // nett 14658 vs วันพุธที่แล้ว 13000 = +12.8% → positive trend headline first.
  ok("advice trend headline WoW-up", a2.advice[0]?.startsWith("ยอดขายสูงกว่าวันพุธที่แล้ว"));

  const mc = analytics.monthComparison(bid2, 2026, 9, "2026-09-30");
  const mtd = 14658 + 13000; // Sept days ≤30 with sales
  ok("month MTD nett", mc.mtdNett === mtd && mc.throughDay === 30);
  ok("month vs prev month (Aug 14000)", near(mc.prevMonthPct ?? 0, ((mtd - 14000) / 14000) * 100));
  ok("month vs last year (Sep2025 50000)", near(mc.lastYearPct ?? 0, ((mtd - 50000) / 50000) * 100));

  // Period toggle (owner 2026-09-18): month vs current ISO week ranges + bundle.
  // Current partial month: same-period window vs last month (owner 2026-09-20).
  const rMonth = analytics.insightRangeFor("month", 2026, 9, "2026-09-16");
  ok("range month same-period 09-01..09-16 vs 08-01..08-16",
    rMonth.start === "2026-09-01" && rMonth.end === "2026-09-16" &&
    rMonth.prevStart === "2026-08-01" && rMonth.prevEnd === "2026-08-16" &&
    rMonth.nowLabel === "เดือนนี้" && rMonth.prevLabel === "เทียบเดือนก่อน");
  // Completed past month: full month vs full prev month (both complete windows).
  const rPastMonth = analytics.insightRangeFor("month", 2026, 8, "2026-09-16");
  ok("range past month full 08-01..08-31 vs 07-01..07-31",
    rPastMonth.start === "2026-08-01" && rPastMonth.end === "2026-08-31" &&
    rPastMonth.prevStart === "2026-07-01" && rPastMonth.prevEnd === "2026-07-31");
  const rWeek = analytics.insightRangeFor("week", 2026, 9, "2026-09-16");
  ok("range week Mon–Sun of 09-16", rWeek.start === "2026-09-14" && rWeek.end === "2026-09-20" && rWeek.prevStart === "2026-09-07" && rWeek.prevEnd === "2026-09-13");
  ok("range week labels", rWeek.nowLabel === "สัปดาห์นี้" && rWeek.prevLabel === "เทียบสัปดาห์ก่อน");
  // Week bundle over bid2: only 09-16 falls in this week; guests computed from it.
  const wkBundle = analytics.insightBundle(bid2, rWeek);
  ok("week bundle discount days = 1 (only 09-16)", wkBundle.discount.days === 1);
  ok("week bundle guests party = 43/23", near(wkBundle.guests.avgPartySize ?? 0, 43 / 23));
  // Month bundle sees both Sept days (09-16 + 09-09).
  const moBundle = analytics.insightBundle(bid2, rMonth);
  ok("month bundle discount days = 2", moBundle.discount.days === 2);

  // แผนดันยอด (owner 2026-09-18). Anchor 2026-09-20 (Sun): trailing 28d =
  // 08-23..09-19 captures 09-16 (14658) + 09-09 (13000) → avg 13829/day. The 3
  // upcoming days are Sun/Mon/Tue; Sunday has weekday history (08-16 = 14000, a
  // Sunday), Mon/Tue fall back to the trailing avg → baseline 14000 + 2×13829.
  const pHard = push.salesPushPlan(bid2, 100000, 3, "2026-09-20");
  const trailAvg = (14658 + 13000) / 2;
  ok("push horizon 3 days 09-20..09-22", pHard.days === 3 && pHard.fromDate === "2026-09-20" && pHard.toDate === "2026-09-22");
  ok("push requiredPerDay = 100000/3", near(pHard.requiredPerDay, 100000 / 3));
  ok("push baseline = Sun weekday avg + 2×trailing avg", near(pHard.baselineProjected, 14000 + 2 * trailAvg));
  ok("push target far above → unrealistic + honest verdict", pHard.verdict === "unrealistic" && pHard.gap > 0 && pHard.advice.some((l) => l.includes("สูงกว่ายอดขายปกติ")));
  // Modest target below the normal run-rate → easy.
  const pEasy = push.salesPushPlan(bid2, 30000, 3, "2026-09-20");
  ok("push target below normal → easy + negative gap", pEasy.verdict === "easy" && pEasy.gap < 0);
  // No history at all → no_data verdict, no baseline.
  const bidEmpty = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('rE','RESTE')").run().lastInsertRowid);
  const pEmpty = push.salesPushPlan(bidEmpty, 50000, 5, "2026-09-20");
  ok("push no history → no_data", pEmpty.verdict === "no_data" && !pEmpty.hasBaseline);

  ok("MoM null when target day absent last month", (() => {
    // 2026-03-31 has no 2026-02-31 counterpart → momPct must be null.
    put("2026-03-31", 9000, 10, 12);
    const a3 = analytics.dailyAnalytics(bid2, "2026-03-31")!;
    return a3.metrics.every((m) => m.momPct === null);
  })());

  // ── 6) A weekday · B momentum · D discount · E channels ──
  // Menu momentum: bid week 09-14..20 vs prev week (09-07..13). Add prev-week
  // menu for คอหมูย่าง so it shows as a faller/riser.
  sdb.upsertMenu(bid, uid, { date: "2026-09-10", dateEnd: "2026-09-10", merchant: "REST",
    categories: [], items: [{ name: "คอหมูย่าง", nett: 4000 }, { name: "ปีกไก่", nett: 100 }] });
  const wk2 = analytics.weeklyAnalytics(bid, "2026-09-16");
  // this week คอหมูย่าง = 2000 (16:1200 + 18:800), prev = 4000 → −50% faller.
  ok("momentum faller คอหมูย่าง −50%", !!wk2.menuFallers.find((m) => m.name === "คอหมูย่าง" && near(m.deltaPct ?? 0, -50)));
  ok("momentum riser ปีกไก่ (1500 vs 100 = +1400%)", !!wk2.menuRisers.find((m) => m.name === "ปีกไก่" && near(m.deltaPct ?? 0, 1400)));

  const wd = analytics.weekdayStats(bid, "2026-09-20", 56);
  ok("weekday stats Mon-first, 7 entries", wd.length === 7 && wd[0].label === "จันทร์");
  ok("weekday Monday avg = 10000 (only 09-14)", near(wd[0].avgNett, 10000) && wd[0].days === 1);

  const di = analytics.discountInsight(bid, 2026, 9);
  ok("discount insight has days", di.days === 4 && di.totalDiscount > 0);

  const cm = analytics.monthChannelMix(bid2, 2026, 9);
  ok("channel mix empty types when none", cm.types.length === 0);
  // channel avg-ticket on bid (has QR/TAKEAWAY types on 09-16 via close_up parse? no — bid types are [])
  ok("channel avgTicket null when qty 0", cm.types.every((t) => t.avgTicket === null || t.avgTicket! >= 0));

  // Deeper insights (owner 2026-09-18) on bid2 (Sept: 09-09 nett13000, 09-16 nett14658).
  const me = analytics.menuEngineering(bid, 2026, 9);
  ok("menuEngineering returns 4 buckets + has items", Array.isArray(me.stars) && (me.stars.length + me.plowhorses.length + me.puzzles.length + me.dogs.length) > 0);
  const conc = analytics.menuConcentration(bid, 2026, 9);
  ok("concentration top5 ≤ 100% + countFor80 ≥ 1", conc.top5Pct != null && conc.top5Pct <= 100.01 && conc.countFor80 >= 1);
  const gm = analytics.guestMetrics(bid2, 2026, 9);
  // Sept bid2: nett 27658, bills (23+21)=44... actually 09-16 bills 23, 09-09 bills 21 → 44; pax 43+40=83.
  ok("guest party size = pax/bills", gm.avgPartySize != null && near(gm.avgPartySize, 83 / 44));
  ok("guest spend/head = nett/pax", gm.avgSpendPerHead != null && near(gm.avgSpendPerHead, 27658 / 83));
  const rh = analytics.rhythmInsight(bid2, 2026, 9);
  ok("rhythm payday split present", rh.paydayDays >= 0);
  const bv = analytics.beverageMix(bid2, 2026, 9);
  ok("beverage mix shares sum ~100 when total>0", bv.total === 0 || near(bv.foodPct + bv.beveragePct + bv.dessertPct, 100));
  const q = analytics.qualitySignal(bid2, 2026, 9);
  ok("quality void rate computed (0 here)", q.voidRatePct != null && q.voidRatePct >= 0);

  // ── 7) C target progress · F monthly card ──
  const mo = analytics.monthlyAnalytics(bid2, 2026, 9);
  ok("monthly total (14658+13000)", mo.totalNett === 27658 && mo.dayCount === 2);
  ok("monthly vs prev month (Aug 14000)", near(mo.prevMonthPct ?? 0, ((27658 - 14000) / 14000) * 100));
  ok("monthly vs last year (2025-09 50000)", near(mo.lastYearPct ?? 0, ((27658 - 50000) / 50000) * 100));
  ok("monthly label full Thai", mo.label === "กันยายน 2569" && mo.ym === "2026-09");

  const tp = analytics.targetProgress(60000, 30000, 15, 2026, 9)!;
  ok("target pctOfTarget 50%", near(tp.pctOfTarget, 50));
  ok("target projection 30000/15*30=60000", near(tp.projectedNett, 60000) && tp.onTrack === true);
  ok("targetProgress null when target<=0", analytics.targetProgress(0, 100, 5, 2026, 9) === null);

  ok("monthly target setting round-trip", (() => {
    sdb.setMonthlyTarget(bid2, 500000);
    const got = sdb.getMonthlyTarget(bid2) === 500000;
    sdb.setMonthlyTarget(bid2, null);
    return got && sdb.getMonthlyTarget(bid2) === null;
  })());
  ok("monthly sent round-trip", (() => {
    sdb.markMonthlySent(bid2, "2026-09", uid);
    return sdb.monthlySentAt(bid2, "2026-09") != null;
  })());
  ok("merchant name round-trip + clear", (() => {
    sdb.setMerchantName(bid2, "  HYPOPLARAEMIA  ");
    const got = sdb.getMerchantName(bid2) === "HYPOPLARAEMIA";
    sdb.setMerchantName(bid2, "");
    return got && sdb.getMerchantName(bid2) === null;
  })());
  ok("listDayMerchants returns per-day merchant (for wrong-shop cleanup)", (() => {
    const rows = sdb.listDayMerchants(bid2);
    return rows.length > 0 && rows.every((r) => r.merchant === "R2");
  })());
  ok("card colour: valid hex stored, invalid rejected", (() => {
    sdb.setCardColor(bid2, "#1E3A5F");
    const good = sdb.getCardColor(bid2) === "#1e3a5f";
    sdb.setCardColor(bid2, "not-a-color");
    const rejected = sdb.getCardColor(bid2) === null;
    return good && rejected;
  })());

  // ── 8) Receipt DB + insights (hourly / units / basket, excl STAFF) ──
  const bid4 = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('r4','REST4')").run().lastInsertRowid);
  const rbuf2 = receiptBuf("17/09/2026", "R4", [
    { time: "17/09/2026 12:07:20", no: "1", table: "G2", gross: "1000", discount: "-100", nett: "1000", payment: "PromptPay", items: "1x A,1x B,2x C" },
    { time: "17/09/2026 12:40:00", no: "2", table: "S4", gross: "600", discount: "0", nett: "600", payment: "PromptPay", items: "1x A,1x C" },
    { time: "17/09/2026 19:30:00", no: "3", table: "C2", gross: "800", discount: "0", nett: "800", payment: "PromptPay", items: "1x A,1x B" },
    { time: "17/09/2026 20:00:00", no: "4", table: "STAFF", gross: "300", discount: "-300", nett: "0", payment: "", items: "5x A,5x B" }
  ]);
  const rParsed = parse.parseSalesFile(rbuf2);
  if (rParsed.kind === "receipt") sdb.upsertReceipts(bid4, uid, rParsed.receipt);
  ok("upsertReceipts sets has_receipt", sdb.getDaily(bid4, "2026-09-17")?.has_receipt === 1);
  const ri = analytics.receiptInsights(bid4, 2026, 9);
  ok("receipt hasData + peak hour 12 (1600>800)", ri.hasData && ri.peakHour === 12);
  ok("hourly 12:00 has 2 bills", ri.hourly.find((h) => h.hour === 12)?.bills === 2);
  // Item units excl staff: A=1+1+1=3, B=1+1=2, C=2+1=3 (staff A/B not counted)
  ok("item units exclude staff (A=3)", ri.topUnits.find((u) => u.name === "A")?.units === 3);
  ok("item units B=2 (staff 5 excluded)", ri.topUnits.find((u) => u.name === "B")?.units === 2);
  // Basket: A+B appears in bills 1,3 = 2; A+C in bills 1,2 = 2 (staff excluded)
  ok("basket pair A+B count 2", !!ri.basket.find((p) => (p.a === "A" && p.b === "B") && p.count === 2));
  ok("clearDay removes receipts too", (() => { sdb.clearDay(bid4, "2026-09-17"); return !analytics.receiptInsights(bid4, 2026, 9).hasData; })());

  // ── 9) Menu engineering: จำนวนจาน joined from receipts by name (owner 2026-09-19) ──
  const bid5 = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('r5','REST5')").run().lastInsertRowid);
  sdb.upsertMenu(bid5, uid, { date: "2026-09-16", dateEnd: "2026-09-16", merchant: "R5",
    categories: [], items: [{ name: "A", nett: 1000 }, { name: "B", nett: 500 }] });
  const rbuf3 = parse.parseSalesFile(receiptBuf("16/09/2026", "R5", [
    { time: "16/09/2026 12:00:00", no: "1", table: "T1", gross: "1500", discount: "0", nett: "1500", payment: "Cash", items: "3x A,2x B" }
  ]));
  if (rbuf3.kind === "receipt") sdb.upsertReceipts(bid5, uid, rbuf3.receipt);
  const me5 = analytics.menuEngineering(bid5, 2026, 9);
  const meAll = [...me5.stars, ...me5.plowhorses, ...me5.puzzles, ...me5.dogs];
  ok("menu engineering units A=3 (from receipts)", meAll.find((m) => m.name === "A")?.units === 3);
  ok("menu engineering units B=2 (from receipts)", meAll.find((m) => m.name === "B")?.units === 2);
  // No receipts for bid's menu names → units null.
  const meNoRcpt = analytics.menuEngineering(bid, 2026, 9);
  ok("menu engineering units null without receipts", [...meNoRcpt.stars, ...meNoRcpt.plowhorses, ...meNoRcpt.puzzles, ...meNoRcpt.dogs].every((m) => m.units === null));

  // ── 10) existingKinds: dup-import guard flags (owner 2026-09-19) ──
  const bid6 = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('r6','REST6')").run().lastInsertRowid);
  ok("existingKinds all false when empty", (() => { const e = sdb.existingKinds(bid6, "2026-09-16"); return !e.sales && !e.menu && !e.receipt; })());
  sdb.upsertDaily(bid6, uid, { date: "2026-09-16", dateEnd: "2026-09-16", merchant: "R6", nett: 100, gross: 100, grossBeforeCharges: 100, discount: 0, serviceCharge: 0, vat: 0, rounding: 0, deliveryFee: 0, otherCharge: 0, billCount: 1, pax: 1, voidAmount: 0, voidBillCount: 0, refund: 0, avgSales: 100, avgPax: 1, avgSalesPax: 100, payments: [], types: [], sources: [] });
  ok("existingKinds sales true after close_up (menu still false)", (() => { const e = sdb.existingKinds(bid6, "2026-09-16"); return e.sales === true && e.menu === false; })());
  sdb.upsertMenu(bid6, uid, { date: "2026-09-16", dateEnd: "2026-09-16", merchant: "R6", categories: [], items: [{ name: "A", nett: 100 }] });
  ok("existingKinds menu true after overview", sdb.existingKinds(bid6, "2026-09-16").menu === true);
  const rbuf6 = parse.parseSalesFile(receiptBuf("16/09/2026", "R6", [
    { time: "16/09/2026 12:00:00", no: "1", table: "T1", gross: "100", discount: "0", nett: "100", payment: "Cash", items: "1x A" }
  ]));
  if (rbuf6.kind === "receipt") sdb.upsertReceipts(bid6, uid, rbuf6.receipt);
  ok("existingKinds receipt true after receipt", sdb.existingKinds(bid6, "2026-09-16").receipt === true);
  ok("existingKinds other date still all false", (() => { const e = sdb.existingKinds(bid6, "2026-09-17"); return !e.sales && !e.menu && !e.receipt; })());

  // ── 11) annualProjection (owner 2026-09-20): full-year target = monthly × 12
  // for an established branch (no opens_on this year → not prorated). ──
  const mkDay = (bid: number, d: string, nett: number) => sdb.upsertDaily(bid, uid, { date: d, dateEnd: d, merchant: "RY", nett, gross: nett, grossBeforeCharges: nett, discount: 0, serviceCharge: 0, vat: 0, rounding: 0, deliveryFee: 0, otherCharge: 0, billCount: 10, pax: 18, voidAmount: 0, voidBillCount: 0, refund: 0, avgSales: nett / 10, avgPax: 1.8, avgSalesPax: nett / 18, payments: [], types: [], sources: [] });
  const bid7 = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('r7','REST7')").run().lastInsertRowid);
  sdb.setMonthlyTarget(bid7, 100000);
  mkDay(bid7, "2026-01-15", 50000);
  const ap = analytics.annualProjection(bid7, "2026-01-31");
  ok("annual target = monthly × 12 (no opens_on → full year)", ap?.annualTarget === 1200000 && ap?.prorated === false);
  ok("annual ytd = 50000", ap?.ytdNett === 50000);
  // Active span Jan15→Jan31 = 17 days; project the remaining 334 days at that rate.
  ok("annual projected uses branch's active span", ap != null && near(ap.projectedNett, 50000 + (50000 / 17) * 334));
  ok("annual pct of target ≈ 4.17", ap != null && near(ap.pctOfTarget, (50000 / 1200000) * 100));
  const bidNoTgt = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('rnt','RESTNT')").run().lastInsertRowid);
  ok("annual no target → null", analytics.annualProjection(bidNoTgt, "2026-01-31") === null);
  const bid8 = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('r8','REST8')").run().lastInsertRowid);
  sdb.setMonthlyTarget(bid8, 200000);
  mkDay(bid8, "2026-01-20", 30000);
  const co = analytics.annualProjectionForBranches([bid7, bid8, bidNoTgt], "2026-01-31");
  ok("company annual target = (100k+200k)×12", co?.annualTarget === 3600000);
  ok("company annual ytd = 80000", co?.ytdNett === 80000);
  ok("company branchCount counts only targeted branches (2)", co?.branchCount === 2);
  // Each branch projected on its own span (bid7 Jan15→17d, bid8 Jan20→12d) then summed.
  ok("company projection = sum of per-branch projections", co != null && near(co.projectedNett, (50000 + (50000 / 17) * 334) + (30000 + (30000 / 12) * 334)));

  // ── 12) menu-name merging (owner 2026-09-20): "ตับหวาน" vs "ตับหวานอัลตราสมูธ" ──
  const names = await import("../src/lib/salesa-names");
  ok("similarity: one contains the other → 'contains'", names.nameSimilarity("ตับหวาน", "ตับหวานอัลตราสมูธ").reason === "contains");
  ok("similarity: identical after normalize → 'exact'", names.nameSimilarity("  โค้ก ", "โค้ก").reason === "exact");
  ok("similarity: unrelated → 'none'", names.nameSimilarity("ข้าวสวย", "ปลาทูทอด").reason === "none");
  ok("groupLabel joins shortest-first", names.groupLabel(["ตับหวานอัลตราสมูธ", "ตับหวาน"]) === "ตับหวาน / ตับหวานอัลตราสมูธ");
  ok("pairKey is order-independent", names.pairKey("a", "b") === names.pairKey("b", "a"));
  ok("editDistance basic", names.editDistance("kitten", "sitting") === 3);

  const bidM = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('rm','RESTM')").run().lastInsertRowid);
  sdb.upsertMenu(bidM, uid, { date: "2026-09-10", dateEnd: "2026-09-10", merchant: "RM", categories: [], items: [{ name: "ตับหวาน", nett: 300 }] });
  sdb.upsertMenu(bidM, uid, { date: "2026-09-12", dateEnd: "2026-09-12", merchant: "RM", categories: [], items: [{ name: "ตับหวานอัลตราสมูธ", nett: 200 }, { name: "ข้าวสวย", nett: 50 }] });
  ok("before merge: two separate item lines", (() => {
    const r = sdb.menuRange(bidM, "2026-09-01", "2026-09-30", "item");
    return r.some((x) => x.name === "ตับหวาน") && r.some((x) => x.name === "ตับหวานอัลตราสมูธ");
  })());
  ok("suggestMenuMerges surfaces the similar pair", (() => {
    const s = sdb.suggestMenuMerges(bidM);
    return s.some((p) => [p.a, p.b].includes("ตับหวาน") && [p.a, p.b].includes("ตับหวานอัลตราสมูธ"));
  })());
  sdb.mergeMenuNames(bidM, ["ตับหวาน", "ตับหวานอัลตราสมูธ"], uid);
  ok("after merge: folded under joined label, nett summed (300+200)", (() => {
    const r = sdb.menuRange(bidM, "2026-09-01", "2026-09-30", "item");
    const g = r.find((x) => x.name === "ตับหวาน / ตับหวานอัลตราสมูธ");
    return !!g && near(g.nett, 500) && !r.some((x) => x.name === "ตับหวานอัลตราสมูธ");
  })());
  ok("merged pair no longer suggested", !sdb.suggestMenuMerges(bidM).some((p) => [p.a, p.b].includes("ตับหวาน")));
  ok("listMenuGroups shows the group with both members", (() => {
    const g = sdb.listMenuGroups(bidM);
    return g.length === 1 && g[0].members.length === 2 && g[0].label === "ตับหวาน / ตับหวานอัลตราสมูธ";
  })());
  sdb.upsertMenu(bidM, uid, { date: "2026-09-14", dateEnd: "2026-09-14", merchant: "RM", categories: [], items: [{ name: "ตับหวาน", nett: 100 }, { name: "ตับหวานอัลตราสมูธ", nett: 40 }] });
  ok("getMenu folds same-day spellings (100+40)", (() => {
    const m = sdb.getMenu(bidM, "2026-09-14");
    const g = m.items.find((i) => i.name === "ตับหวาน / ตับหวานอัลตราสมูธ");
    return !!g && near(g.nett, 140) && m.items.filter((i) => i.name.includes("ตับหวาน")).length === 1;
  })());
  const rbufM = parse.parseSalesFile(receiptBuf("15/09/2026", "RM", [
    { time: "15/09/2026 12:00:00", no: "1", table: "T1", gross: "300", discount: "0", nett: "300", payment: "Cash", items: "1x ตับหวาน,1x ข้าวสวย" },
    { time: "15/09/2026 13:00:00", no: "2", table: "T2", gross: "200", discount: "0", nett: "200", payment: "Cash", items: "2x ตับหวานอัลตราสมูธ" }
  ]));
  if (rbufM.kind === "receipt") sdb.upsertReceipts(bidM, uid, rbufM.receipt);
  ok("itemUnitsRange folds units across spellings (1+2=3, bills=2)", (() => {
    const g = sdb.itemUnitsRange(bidM, "2026-09-01", "2026-09-30").find((x) => x.name === "ตับหวาน / ตับหวานอัลตราสมูธ");
    return !!g && g.units === 3 && g.bills === 2;
  })());
  sdb.unmergeMenuGroup(bidM, sdb.listMenuGroups(bidM)[0].root);
  ok("after unmerge: names split again", (() => {
    const r = sdb.menuRange(bidM, "2026-09-01", "2026-09-30", "item");
    return r.some((x) => x.name === "ตับหวาน") && r.some((x) => x.name === "ตับหวานอัลตราสมูธ");
  })());
  sdb.ignoreMenuPair(bidM, "ตับหวาน", "ตับหวานอัลตราสมูธ", uid);
  ok("ignored pair is not suggested again", !sdb.suggestMenuMerges(bidM).some((p) => [p.a, p.b].includes("ตับหวาน") && [p.a, p.b].includes("ตับหวานอัลตราสมูธ")));

  // ── 13) multi-day file detection (owner 2026-09-20): a range export (e.g. 15–20
  // ก.ย. in one file) must be distinguishable so the import route can reject it. ──
  const multiPre = (title: string) => [[title], ["Date: 15/09/2026 - 20/09/2026"], ["Time: 00:00 - 23:59"], ["Merchant: TESTBR"], ["Generated by: test"], []];
  const multiOv = parse.parseSalesFile(wbBuf({
    "1.Top products": [...multiPre("Overview"), ["Dataset", "ย่าง"], ["Nett", "100"]],
    "4.Top products": [...multiPre("Overview"), ["Name", "Value"], ["ก", "10"]]
  }));
  ok("multi-day overview → date != dateEnd (import rejects)",
    multiOv.kind === "overview" && multiOv.overview.date === "2026-09-15" && multiOv.overview.dateEnd === "2026-09-20");
  const singleOv = parse.parseOverview(overviewBuf("16/09/2026", "TESTBR", [["ก", "10"]], [["ย่าง", "20"]]));
  ok("single-day overview → date == dateEnd (import accepts)", singleOv.date === singleOv.dateEnd && singleOv.date === "2026-09-16");

  // ── 14) festival / important-day analysis (owner 2026-09-20): per วันสำคัญ,
  // each branch's sales that day vs its month average (uplift %); only past
  // dates with sales appear; future festivals are hidden. ──
  const fbA = Number(db.prepare("INSERT INTO branches (slug,name,display_order) VALUES ('fa','FEST-A',1)").run().lastInsertRowid);
  const fbB = Number(db.prepare("INSERT INTO branches (slug,name,display_order) VALUES ('fb','FEST-B',2)").run().lastInsertRowid);
  const fput = (bid: number, d: string, nett: number) => sdb.upsertDaily(bid, uid, { date: d, dateEnd: d, merchant: "FST", nett, gross: nett, grossBeforeCharges: nett, discount: 0, serviceCharge: 0, vat: 0, rounding: 0, deliveryFee: 0, otherCharge: 0, billCount: 10, pax: 18, voidAmount: 0, voidBillCount: 0, refund: 0, avgSales: nett / 10, avgPax: 1.8, avgSalesPax: nett / 18, payments: [], types: [], sources: [] });
  // Songkran 13 Apr: branch A spikes (300 vs 100-avg → +200%), branch B flat (100 vs 100 → 0%).
  db.prepare("INSERT OR REPLACE INTO public_holidays (date, name_th, name_en) VALUES (?,?,?)").run("2026-04-13", "วันสงกรานต์", "Songkran");
  fput(fbA, "2026-04-13", 300); fput(fbA, "2026-04-14", 100); fput(fbA, "2026-04-15", 100);
  fput(fbB, "2026-04-13", 100); fput(fbB, "2026-04-14", 100); fput(fbB, "2026-04-15", 100);
  // A festival with no sales at all (both branches) — must be dropped from the table.
  db.prepare("INSERT OR REPLACE INTO public_holidays (date, name_th, name_en) VALUES (?,?,?)").run("2026-01-01", "วันขึ้นปีใหม่", "New Year");
  // A future festival (after today 2026-09-20) — even if seeded, must be excluded.
  db.prepare("INSERT OR REPLACE INTO public_holidays (date, name_th, name_en) VALUES (?,?,?)").run("2026-12-31", "วันสิ้นปี", "NYE");
  fput(fbA, "2026-12-31", 500);
  const fa = analytics.festivalAnalysis(2026, "2026-09-20");
  ok("festival: branch A ordered before branch B (display_order)", (() => {
    const ids = fa.branches.map((b) => b.id);
    const ia = ids.indexOf(fbA), ib = ids.indexOf(fbB);
    return ia >= 0 && ib >= 0 && ia < ib;
  })());
  const songkran = fa.rows.find((r) => r.date === "2026-04-13");
  ok("festival: Songkran row present with Thai name", !!songkran && songkran.nameTh === "วันสงกรานต์");
  ok("festival: branch A uplift +200% on Songkran", (() => {
    const c = songkran?.branches.find((x) => x.branchId === fbA);
    return !!c && c.sales === 300 && near(c.monthAvg ?? -1, 100) && c.upliftPct === 200;
  })());
  ok("festival: branch B flat (0% uplift)", (() => {
    const c = songkran?.branches.find((x) => x.branchId === fbB);
    return !!c && c.sales === 100 && c.upliftPct === 0;
  })());
  ok("festival: no-sales festival (New Year) dropped", !fa.rows.some((r) => r.date === "2026-01-01"));
  ok("festival: future festival (NYE) excluded", !fa.rows.some((r) => r.date === "2026-12-31"));
  const faScoped = analytics.festivalAnalysis(2026, "2026-09-20", [fbB]);
  ok("festival: allowedBranchIds scopes columns to branch B only",
    faScoped.branches.length === 1 && faScoped.branches[0].id === fbB &&
    (faScoped.rows.find((r) => r.date === "2026-04-13")?.branches.length === 1));

  // ── 15) annual target prorated to a branch's open span (owner 2026-09-21):
  // a branch whose branches.opens_on is mid-year (ไฮโปเปิด 25/07) must not be
  // judged against a full-year monthly×12 target — prorate to (opens_on → 31 ธ.ค.).
  // Keyed off opens_on, NOT first sale (SALESA data only starts in 2026). ──
  const fput2 = (bid: number, d: string, nett: number) => sdb.upsertDaily(bid, uid, { date: d, dateEnd: d, merchant: "OPEN", nett, gross: nett, grossBeforeCharges: nett, discount: 0, serviceCharge: 0, vat: 0, rounding: 0, deliveryFee: 0, otherCharge: 0, billCount: 5, pax: 9, voidAmount: 0, voidBillCount: 0, refund: 0, avgSales: nett / 5, avgPax: 1.8, avgSalesPax: nett / 9, payments: [], types: [], sources: [] });
  // New branch: monthly target 600k, opened 25/07/2026 (opens_on set).
  const bidNew = Number(db.prepare("INSERT INTO branches (slug,name,opens_on) VALUES ('opn','HYPOP','2026-07-25')").run().lastInsertRowid);
  sdb.setMonthlyTarget(bidNew, 600000);
  fput2(bidNew, "2026-07-25", 20000); fput2(bidNew, "2026-08-10", 25000);
  const apNew = analytics.annualProjection(bidNew, "2026-09-20");
  ok("annual: new branch is prorated (opens_on 25/07)", !!apNew && apNew.prorated === true && apNew.openedIso === "2026-07-25");
  ok("annual: new branch full-year figure kept for reference (7.2M)", !!apNew && apNew.fullYearTarget === 7200000);
  ok("annual: new branch target prorated to open span (~3.156M, not 7.2M)", (() => {
    if (!apNew) return false;
    const expect = 7200000 * (160 / 365); // 25 ก.ค.→31 ธ.ค. = 160 วัน / 365
    return Math.abs(apNew.annualTarget - expect) < 1 && apNew.annualTarget < 7200000;
  })());
  // Established branch: opens_on in a PRIOR year → full ×12, not prorated — even
  // though its imported SALESA data only starts in 2026.
  const bidOld = Number(db.prepare("INSERT INTO branches (slug,name,opens_on) VALUES ('est','ESTAB','2024-01-01')").run().lastInsertRowid);
  sdb.setMonthlyTarget(bidOld, 500000);
  fput2(bidOld, "2026-02-01", 30000);
  const apOld = analytics.annualProjection(bidOld, "2026-09-20");
  ok("annual: established branch (opens_on prior year) NOT prorated (full 6M)", !!apOld && apOld.prorated === false && apOld.annualTarget === 6000000 && apOld.openedIso === null);
  // Company roll-up flags proration when any branch opened mid-year.
  const apCo = analytics.annualProjectionForBranches([bidNew, bidOld], "2026-09-20");
  ok("annual: company roll-up flags prorated + sums both targets", (() => {
    if (!apCo) return false;
    const expect = 7200000 * (160 / 365) + 6000000;
    return apCo.prorated === true && apCo.branchCount === 2 && Math.abs(apCo.annualTarget - expect) < 1 && apCo.fullYearTarget === 13200000;
  })());

  // ── 16) full-year growth bars (owner 2026-09-21): per-branch monthly nett,
  // Jan → last month with data, for reading each branch's growth trend. ──
  const fput3 = (bid: number, d: string, nett: number) => sdb.upsertDaily(bid, uid, { date: d, dateEnd: d, merchant: "BAR", nett, gross: nett, grossBeforeCharges: nett, discount: 0, serviceCharge: 0, vat: 0, rounding: 0, deliveryFee: 0, otherCharge: 0, billCount: 4, pax: 7, voidAmount: 0, voidBillCount: 0, refund: 0, avgSales: nett / 4, avgPax: 1.8, avgSalesPax: nett / 7, payments: [], types: [], sources: [] });
  const bidBar = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('bar','BARBR')").run().lastInsertRowid);
  fput3(bidBar, "2026-01-10", 10000); fput3(bidBar, "2026-01-20", 10000); // Jan 20000
  fput3(bidBar, "2026-02-14", 30000);                                     // Feb 30000 (peak)
  fput3(bidBar, "2026-03-05", 15000);                                     // Mar 15000
  fput3(bidBar, "2026-09-03", 5000);                                      // Sep 5000 (current, partial)
  const yb = analytics.annualBranchBars(2026, "2026-09-20", [bidBar]);
  ok("yearbars: monthCount = through current month (Sep → 9)", yb.monthCount === 9);
  ok("yearbars: monthly nett Jan/Feb/Mar + current Sep bar", (() => {
    const b = yb.branches.find((x) => x.branchId === bidBar);
    return !!b && b.months[0] === 20000 && b.months[1] === 30000 && b.months[2] === 15000 && b.months[3] === null && b.months[8] === 5000;
  })());
  ok("yearbars: growth ignores in-progress Sep (Jan→Mar −25%, not Jan→Sep)", (() => {
    const b = yb.branches.find((x) => x.branchId === bidBar);
    return !!b && b.total === 70000 && b.peakMonth === 2 && b.growthPct === -25;
  })());
  ok("yearbars: past year renders all 12 months", analytics.annualBranchBars(2025, "2026-09-20").monthCount === 12);
  ok("yearbars: allowedBranchIds scopes to that branch only",
    yb.branches.length === 1 && yb.branches[0].branchId === bidBar);

  // ── 16b) full-year DAILY bars (owner 2026-09-21): one bar per calendar day. ──
  const dbars = analytics.annualBranchDailyBars(2026, "2026-09-20", [bidBar]);
  ok("dailybars: dayCount = day-of-year of today (Sep 20 → 263)", dbars.dayCount === 263 && dbars.startIso === "2026-01-01");
  ok("dailybars: each sale day maps to its index; empty days are null", (() => {
    const b = dbars.branches.find((x) => x.branchId === bidBar);
    if (!b) return false;
    const idx = (iso: string) => Math.floor((Date.UTC(2026, Number(iso.slice(5, 7)) - 1, Number(iso.slice(8, 10))) - Date.UTC(2026, 0, 1)) / 86_400_000);
    return b.values[idx("2026-01-10")] === 10000 && b.values[idx("2026-02-14")] === 30000
      && b.values[idx("2026-09-03")] === 5000 && b.values[idx("2026-01-11")] === null;
  })());
  ok("dailybars: total + peak (Feb 14) + low (Sep 3, 5000) + avg over 5 days", (() => {
    const b = dbars.branches.find((x) => x.branchId === bidBar);
    if (!b) return false;
    const feb14 = Math.floor((Date.UTC(2026, 1, 14) - Date.UTC(2026, 0, 1)) / 86_400_000);
    const sep3 = Math.floor((Date.UTC(2026, 8, 3) - Date.UTC(2026, 0, 1)) / 86_400_000);
    return b.total === 70000 && b.peakIdx === feb14 && b.lowIdx === sep3 && b.avgPerDay === 14000;
  })());
  ok("dailybars: past year spans all 365 days", analytics.annualBranchDailyBars(2025, "2026-09-20").dayCount === 365);

  // ── 17) company overview (owner 2026-09-21): cross-branch roll-up — company
  // MTD total, same-period MoM compare, per-branch rows, company target. ──
  const fputC = (bid: number, d: string, nett: number, bills: number, pax: number) => sdb.upsertDaily(bid, uid, { date: d, dateEnd: d, merchant: "CO", nett, gross: nett, grossBeforeCharges: nett, discount: 0, serviceCharge: 0, vat: 0, rounding: 0, deliveryFee: 0, otherCharge: 0, billCount: bills, pax, voidAmount: 0, voidBillCount: 0, refund: 0, avgSales: nett / bills, avgPax: pax / bills, avgSalesPax: nett / pax, payments: [], types: [], sources: [] });
  const bidCA = Number(db.prepare("INSERT INTO branches (slug,name,display_order) VALUES ('coa','CO-A',1)").run().lastInsertRowid);
  const bidCB = Number(db.prepare("INSERT INTO branches (slug,name,display_order) VALUES ('cob','CO-B',2)").run().lastInsertRowid);
  sdb.setMonthlyTarget(bidCA, 100000);
  fputC(bidCA, "2026-09-05", 10000, 8, 12); fputC(bidCA, "2026-09-20", 5000, 4, 6); // Sept 1–20 = 15000
  fputC(bidCA, "2026-08-10", 20000, 10, 15);                                          // Aug 1–20 = 20000 (prev same)
  fputC(bidCB, "2026-09-15", 8000, 6, 9);                                             // Sept = 8000, no Aug
  const cov = analytics.companyOverview([bidCA, bidCB], 2026, 9, "2026-09-20");
  ok("company: window through today (Sep 20)", cov.throughDay === 20 && cov.isCurrentMonth === true && cov.branchCount === 2);
  ok("company: total MTD = 23000, bills=18", cov.total.mtdNett === 23000 && cov.total.bills === 18);
  // Same-store: B has no prior-month data → excluded from the % compare, so the
  // company MoM reflects A only (15000 vs 20000 = −25%), not the inflated +15%.
  ok("company: same-store prev = 20000, MoM = −25% (new branch excluded)", cov.total.prevSameNett === 20000 && cov.total.momPct === -25);
  ok("company: today total (rows on 20 Sep) = 5000", cov.total.todayNett === 5000);
  ok("company: only A is targeted, company target = 100000", cov.targetedBranchCount === 1 && cov.target != null && cov.target.target === 100000);
  ok("company: branch A row (MTD 15000, MoM −25%, ทำได้ 15%)", (() => {
    const a = cov.branches.find((b) => b.branchId === bidCA);
    return !!a && a.mtdNett === 15000 && a.prevSameNett === 20000 && a.momPct === -25 && a.monthTarget === 100000 && a.pctOfTarget === 15 && a.todayNett === 5000;
  })());
  ok("company: branch B row (no prev, no target)", (() => {
    const b = cov.branches.find((x) => x.branchId === bidCB);
    return !!b && b.mtdNett === 8000 && b.prevSameNett === null && b.momPct === null && b.monthTarget === null && b.todayNett === 0;
  })());
  ok("company: branches ordered A before B (display_order)", (() => {
    const ids = cov.branches.map((b) => b.branchId);
    return ids.indexOf(bidCA) < ids.indexOf(bidCB);
  })());
  // Past month → window through the latest imported day (Aug: A imported the 10th).
  const covAug = analytics.companyOverview([bidCA, bidCB], 2026, 8, "2026-09-20");
  ok("company: past month window = max imported day (Aug 10)", covAug.throughDay === 10 && covAug.isCurrentMonth === false && covAug.total.mtdNett === 20000);
  // Past year → no annual roll-up (projection only makes sense for the current year).
  ok("company: past-year view has no annual roll-up", analytics.companyOverview([bidCA, bidCB], 2025, 9, "2026-09-20").annual === null);

  // ── 18) company weekly same-period compare (owner 2026-09-21): this ISO week
  // Mon..today vs the previous week's identical day-window. ──
  const bidWA = Number(db.prepare("INSERT INTO branches (slug,name,display_order) VALUES ('wka','WK-A',1)").run().lastInsertRowid);
  const bidWB = Number(db.prepare("INSERT INTO branches (slug,name,display_order) VALUES ('wkb','WK-B',2)").run().lastInsertRowid);
  fputC(bidWA, "2026-09-15", 12000, 10, 15);  // this week (Mon 14..Wed 16)
  fputC(bidWB, "2026-09-16", 8000, 6, 9);      // this week, B only
  fputC(bidWA, "2026-09-08", 10000, 8, 12);    // last week same window (Mon 07..Wed 09)
  const cwk = analytics.companyWeekCompare([bidWA, bidWB], "2026-09-16");
  ok("week: window Mon..today (09-14..09-16, 3 วัน)", cwk.weekStart === "2026-09-14" && cwk.throughIso === "2026-09-16" && cwk.dayCount === 3);
  ok("week: company nett 20000, same-store WoW +20% (12000 vs 10000)", cwk.total.nett === 20000 && cwk.total.prevNett === 10000 && cwk.total.wowPct === 20);
  ok("week: WA +20% (12000 vs 10000), WB has no prior week", (() => {
    const a = cwk.branches.find((b) => b.branchId === bidWA), b = cwk.branches.find((x) => x.branchId === bidWB);
    return !!a && a.nett === 12000 && a.prevNett === 10000 && a.wowPct === 20 && !!b && b.nett === 8000 && b.prevNett === null && b.wowPct === null;
  })());

  // ── 19) company top menu / categories รวมทุกสาขา (owner 2026-09-21) ──
  const bidM1 = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('tm1','TM-1')").run().lastInsertRowid);
  const bidM2 = Number(db.prepare("INSERT INTO branches (slug,name) VALUES ('tm2','TM-2')").run().lastInsertRowid);
  sdb.upsertMenu(bidM1, uid, { date: "2026-09-10", dateEnd: "2026-09-10", merchant: "TM1", categories: [{ name: "ต้ม", nett: 100 }], items: [{ name: "ต้มยำ", nett: 100 }] });
  sdb.upsertMenu(bidM2, uid, { date: "2026-09-11", dateEnd: "2026-09-11", merchant: "TM2", categories: [{ name: "ต้ม", nett: 50 }, { name: "ผัด", nett: 80 }], items: [{ name: "ต้มยำ", nett: 50 }, { name: "ผัดไทย", nett: 80 }] });
  const tm = analytics.companyTopMenu([bidM1, bidM2], "2026-09-01", "2026-09-30");
  ok("topmenu: ต้มยำ merged across 2 branches (150), ผัดไทย 80 (1 branch)", (() => {
    const a = tm.items[0], b = tm.items[1];
    return a.name === "ต้มยำ" && a.nett === 150 && a.branchCount === 2 && b.name === "ผัดไทย" && b.nett === 80 && b.branchCount === 1;
  })());
  ok("topmenu: category ต้ม 150 (2), ผัด 80 (1)", (() => {
    const a = tm.categories[0], b = tm.categories[1];
    return a.name === "ต้ม" && a.nett === 150 && a.branchCount === 2 && b.name === "ผัด" && b.nett === 80 && b.branchCount === 1;
  })());

  console.log(`\n${failed === 0 ? "✓ ALL PASS" : "✗ FAILURES"} — ${passed} passed, ${failed} failed`);
  cleanup();
  process.exit(failed === 0 ? 0 : 1);
})();
